//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by demo_res.rc
//
#define IDS_PROPPAGE_ENCODE_FORMAT      101
#define IDS_PROPPAGE_ENCODE_PARAM       102
#define IDS_PROPPAGE_ABOUT              103
#define IDS_PROPPAGE_IMG_PARAM          104
#define IDS_PROPPAGE_MD_PARAM           105
#define IDS_PROPPAGE_MUXER_PARAM        106
#define IDD_DIALOG_ABOUT                132
#define IDB_BITMAP_LOGO                 133
#define IDD_DIALOG_ENCODE_FORMAT        135
#define IDD_DIALOG_ENCODE_PARAM         136
#define IDD_DIALOG_IMG_PARAM            137
#define IDD_DIALOG_MD_PARAM             138
#define IDD_DIALOG_MUXER_PARAM          139
#define IDC_COMBO_SENSOR_INPUT_MODE     1019
#define IDC_COMBO_FRAME_RATE            1020
#define IDC_COMBO_SENSOR_INPUT_MODE2    1021
#define IDC_COMBO_SENSOR_MIRROR_PATTERN 1021
#define IDC_COMBO_SENSOR_BAYER_PATTERN  1022
#define IDC_COMBO_RESOLUTION_VOUT       1025
#define IDC_STATIC_SENSOR_INPUT_MODE    1028
#define IDC_STATIC_FRAME_RATE           1029
#define IDC_STATIC_SENSOR_MIRROR_PATTERN 1030
#define IDC_STATIC_SENSOR_BAYER_PATTERN 1031
#define IDC_STATIC_RESOLUTION_VOUT      1034
#define IDC_COMBO1                      1035
#define IDC_EDIT1                       1036
#define IDC_EDIT2                       1037
#define IDC_COMBO2                      1037
#define IDC_RADIO1                      1038
#define IDC_RADIO2                      1039
#define IDC_RADIO3                      1040
#define IDC_EDIT3                       1041
#define IDC_EDIT4                       1042
#define IDC_RADIO10                     1042
#define IDC_RADIO4                      1043
#define IDC_EDIT5                       1044
#define IDC_RADIO_ROI4_ON               1044
#define IDC_RADIO5                      1045
#define IDC_EDIT_ROI_RD_X               1045
#define IDC_EDIT_ROI1_RD_X              1045
#define IDC_EDIT6                       1046
#define IDC_EDIT_ROI1_THESH             1046
#define IDC_EDIT_ROI1_THR               1046
#define IDC_RADIO6                      1047
#define IDC_EDIT_ROI1_SENS              1047
#define IDC_COMBO3                      1048
#define IDC_EDIT_ROI2_RD_X              1048
#define IDC_EDIT7                       1049
#define IDC_EDIT_ROI2_THESH             1049
#define IDC_EDIT_ROI2_THR               1049
#define IDC_EDIT8                       1050
#define IDC_EDIT_ROI2_SENS              1050
#define IDC_RADIO7                      1051
#define IDC_EDIT_ROI3_RD_X              1051
#define IDC_RADIO8                      1052
#define IDC_EDIT_ROI3_THESH             1052
#define IDC_EDIT_ROI3_THR               1052
#define IDC_EDIT9                       1053
#define IDC_EDIT_ROI3_SENS              1053
#define IDC_EDIT10                      1054
#define IDC_EDIT_ROI4_RD_X              1054
#define IDC_EDIT11                      1055
#define IDC_EDIT_ROI4_THESH             1055
#define IDC_EDIT_ROI4_THR               1055
#define IDC_EDIT12                      1056
#define IDC_EDIT_ROI4_SENS              1056
#define IDC_EDIT13                      1057
#define IDC_RADIO_ROI4_OFF              1057
#define IDC_BUTTON1                     1058
#define IDC_BUTTON2                     1059
#define IDC_COMBO5                      1059
#define IDC_COMBO_LENS_TYPE             1063
#define IDC_STATIC_ANTI_FLICKER_MODE    1064
#define IDC_RADIO_ANTI_FLICKER_60Hz     1065
#define IDC_RADIO_ANTI_FLICKER_50Hz     1066
#define IDC_STATIC_BLACK_WHITE_MODE     1067
#define IDC_STATIC_ROI_LEFT_UP          1067
#define IDC_STATIC_ROI1                 1067
#define IDC_RADIO_BLACK_WHITE_ON        1068
#define IDC_EDIT_ROI1_LU_X              1068
#define IDC_RADIO_BLACK_WHITE_OFF       1069
#define IDC_STATIC_ROI_RIGHT_DOWN       1069
#define IDC_EDIT_ROI2_LU_X              1069
#define IDC_STATIC_SLOW_SHUTTER_MODE    1070
#define IDC_EDIT_ROI_LU_Y               1070
#define IDC_EDIT_ROI1_LU_Y              1070
#define IDC_RADIO_SLOW_SHUTTER_ON       1071
#define IDC_EDIT_ROI_RD_Y               1071
#define IDC_EDIT_ROI1_RD_Y              1071
#define IDC_RADIO_SLOW_SHUTTER_OFF      1072
#define IDC_RADIO_MD_SRC_AAA            1072
#define IDC_RADIO_MD_SRC_PREV           1073
#define IDC_STATIC_MD_DATA_SRC          1074
#define IDC_STATIC_ROI_INFO             1075
#define IDC_STATIC_ROI_1                1075
#define IDC_EDIT_ROI2_LU_Y              1076
#define IDC_STATIC_ROI_LEFT_UP2         1077
#define IDC_STATIC_ROI2                 1077
#define IDC_EDIT_ROI2_RD_Y              1078
#define IDC_EDIT_ROI3_LU_X              1079
#define IDC_EDIT_ROI3_LU_Y              1080
#define IDC_STATIC_ROI_LEFT_UP3         1081
#define IDC_STATIC_ROI3                 1081
#define IDC_EDIT_ROI3_RD_Y              1082
#define IDC_EDIT_ROI4_LU_X              1083
#define IDC_EDIT_ROI4_LU_Y              1084
#define IDC_STATIC_ROI_LEFT_UP4         1085
#define IDC_STATIC_ROI4                 1085
#define IDC_EDIT_ROI_RD_Y4              1086
#define IDC_EDIT_ROI4_RD_Y              1086
#define IDC_RADIO_ROI1_ON               1088
#define IDC_RADIO_ROI1_OFF              1089
#define IDC_RADIO_ROI2_ON               1091
#define IDC_MAIN_NONE                   1091
#define IDC_RADIO_ROI2_OFF              1092
#define IDC_MAIN_H264                   1092
#define IDC_MAIN_MJPEG                  1093
#define IDC_RADIO_ROI3_ON               1094
#define IDC_MAIN_RESOLUTION             1094
#define IDC_RADIO_ROI3_OFF              1095
#define IDC_MAIN_FRAME_INTERVAL         1095
#define IDC_RADIO_BLACK_WHITE_AUTO      1096
#define IDC_SECOND_NONE                 1096
#define IDC_RADIO_SLOW_SHUTTER_AUTO     1097
#define IDC_SECOND_H264                 1097
#define IDC_STATIC_3A_ENABLE_MODE       1098
#define IDC_SECOND_MJPEG                1098
#define IDC_RADIO_3A_ENABLE_OFF         1099
#define IDC_SECOND_RESOLUTION           1099
#define IDC_RADIO_3A_ENABLE_ON          1100
#define IDC_MAIN_FRAME_INTERVAL2        1100
#define IDC_SECOND_FRAME_INTERVAL       1100
#define IDC_STATIC_3A_FUNCTION_MODE     1101
#define IDC_VIN_MODE                    1101
#define IDC_RADIO_3A_AE_OFF             1102
#define IDC_VIN_FRAME_RATE              1102
#define IDC_RADIO_3A_AE_ON              1103
#define IDC_VIN_MIRROR_PATTERN          1103
#define IDC_RADIO_3A_AWB_OFF            1104
#define IDC_VIN_BAYER_PATTERN           1104
#define IDC_RADIO_3A_AWB_ON             1105
#define IDC_VOUT_RESOLUTION             1105
#define IDC_RADIO_3A_AF_OFF             1106
#define IDC_RADIO_3A_AF_ON              1107
#define IDC_RADIO_3A_ADJ_OFF            1108
#define IDC_RADIO_3A_ADJ_ON             1109
#define IDC_MAIN_PROFILE_MAIN           1110
#define IDC_MAIN_PROFILE_BASELINE       1111
#define IDC_SECOND_PROFILE_MAIN         1112
#define IDC_SECOND_PROFILE_BASELINE     1113
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        141
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1106
#define _APS_NEXT_SYMED_VALUE           111
#endif
#endif
