obj-$(CONFIG_RPROC_SUPPORT)	+= host/rproc_ambarella.o
obj-$(CONFIG_RPROC_CA9_A)	+= host/rproc_ca9_a.o
obj-$(CONFIG_RPROC_CA9_B)	+= host/rproc_ca9_b.o
obj-$(CONFIG_RPROC_S2)		+= host/rproc_s2.o

obj-$(CONFIG_RPCLNT_SUPPORT)	+= clnt/vq.o
obj-$(CONFIG_RPCLNT_SUPPORT)	+= clnt/rpdev.o
obj-$(CONFIG_RPCLNT_CA9_B)	+= clnt/rpclnt_ca9_b.o
