obj-$(CONFIG_RPROC_SUPPORT) += host/ambxc/
obj-$(CONFIG_RPROC_SUPPORT) += host/aservice/
obj-$(CONFIG_RPROC_SUPPORT) += host/rsh/
obj-$(CONFIG_RPROC_SUPPORT) += host/echo/
obj-$(CONFIG_RPROC_SUPPORT) += host/veth/
obj-$(CONFIG_RPROC_SUPPORT) += host/wnfs/
obj-$(CONFIG_RPROC_SUPPORT) += host/rnfs/
obj-$(CONFIG_RPROC_SUPPORT) += host/vgpio/

obj-$(CONFIG_RPCLNT_SUPPORT) += clnt/rsh/
obj-$(CONFIG_RPCLNT_SUPPORT) += clnt/echo/
obj-$(CONFIG_RPCLNT_SUPPORT) += clnt/veth/

obj-y += common/rsh/
obj-y += common/veth/
