/*
 *
 * adj_container_map.c
 *
 * History:
 *	2015/09/10 - [Jingyang Qiu] Created this file
 *
 * Description :
 *	Load the tuned file which generated by Img tuning tool.
 *
 * Copyright (C) 2015 Ambarella, Inc.
 *
 * This file and its contents ("Software") are protected by intellectual
 * property rights including, without limitation, U.S. and/or foreign
 * copyrights. This Software is also the confidential and proprietary
 * information of Ambarella, Inc. and its licensors. You may not use, reproduce,
 * disclose, distribute, modify, or otherwise prepare derivative works of this
 * Software or any portion thereof except pursuant to a signed license agreement
 * or nondisclosure agreement with Ambarella, Inc. or its authorized affiliates.
 * In the absence of such an agreement, you agree to promptly notify and return
 * this Software to Ambarella, Inc.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF NON-INFRINGEMENT,
 * MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL AMBARELLA, INC. OR ITS AFFILIATES BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; COMPUTER FAILURE OR MALFUNCTION; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 */

typedef enum {
	MAP_TO_U32 = 0,
	MAP_TO_U16,
	MAP_TO_U8,
	MAP_TO_S32,
	MAP_TO_S16,
	MAP_TO_S8,
	MAP_TO_DOUBLE,
	MAP_TO_STRING,
	MAP_DATA_TYPE_NUM,
} mapping_data_type;

typedef struct {
	char * 					TokenName;		// name
	void * 					Address;		// address
	mapping_data_type		Type;			// type: 0 - u32, 1 - u16, 2 - u8, 3 - int(s32), 4 - double, 5 - char[]>
	int						Value_num;
	int						container_id;
//	double					Default;			// default value>
//	mapping_data_constraint	ParamLimits;	// 0 - no limits, 1 - min and max limits, 2 - only min limit, 3 - only max limit
//	double					MinLimit;		// Minimun value
//	double					MaxLimit;		// Maximun value
//	int						StringLengthLimit;	// Dimension of type char[]
} Mapping;

#define INVALID_CONTAINER_ID			0xff

#define MAX_ARGU_U32		1024
#define MAX_ARGU_U8			MAX_ARGU_U32 * 4
#define MAX_STRUCT_MEMBER	8
#define MAX_PARAMS			64

#define	INVALID_OFFSET			(0xff)
#define	TOTAL_STRUCT_NUM		(TOTAL_FILTER_NUM)
#define	READ_ALIGN(value, align)		((value + align -1) / align * align)

#define	TONE_CURVE_SIZE	(256)


typedef struct {
	u8 argu[MAX_ARGU_U8];
	int argu_num;
} parser_t;

static parser_t g_parser[ADJ_FILTER_NUM][MAX_STRUCT_MEMBER];


static Mapping ImgRegs[] = {
	/* ADJ_AE_TARGET 0x160 */

	/* ADJ_WB_RATIO 0x3B8 */

	/* ADJ_BLC 0x610*/
	{"static_black_level.b_black", &g_parser[ADJ_BLC][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_BLC},
	{"static_black_level.g_b_black", &g_parser[ADJ_BLC][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_BLC},
	{"static_black_level.g_r_black", &g_parser[ADJ_BLC][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_BLC},
	{"static_black_level.r_black", &g_parser[ADJ_BLC][0].argu[0], MAP_TO_S32, 1, ADJ_BLC},

	/* ADJ_ANTIALIASING */
	{"li_anti_aliasing.enable", &g_parser[ADJ_ANTIALIASING][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_ANTIALIASING},
	{"li_anti_aliasing.log_fractional_correct", &g_parser[ADJ_ANTIALIASING][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_ANTIALIASING},
	{"li_anti_aliasing.thresh", &g_parser[ADJ_ANTIALIASING][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_ANTIALIASING},


	/* ADJ_GRGB_MISMATCH */
	{"li_gb_gr_mismatch_correct.narrow_enable", &g_parser[ADJ_GRGB_MISMATCH][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_GRGB_MISMATCH},
	{"li_gb_gr_mismatch_correct.wide_enable", &g_parser[ADJ_GRGB_MISMATCH][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_GRGB_MISMATCH},
	{"li_gb_gr_mismatch_correct.wide_safety", &g_parser[ADJ_GRGB_MISMATCH][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_GRGB_MISMATCH},
	{"li_gb_gr_mismatch_correct.wide_thresh", &g_parser[ADJ_GRGB_MISMATCH][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_GRGB_MISMATCH},

	/* ADJ_DPC */
	{"li_auto_bad_pixel_correction.correction_method", &g_parser[ADJ_DPC][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_DPC},
	{"li_auto_bad_pixel_correction.dark_pixel_detection_strength", &g_parser[ADJ_DPC][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_DPC},
	{"li_auto_bad_pixel_correction.enable", &g_parser[ADJ_DPC][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_DPC},
	{"li_auto_bad_pixel_correction.hot_pixel_detection_strength", &g_parser[ADJ_DPC][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_DPC},

	/* ADJ_CFANF_LOW */
	{"li_cfa_noise_filter.enable", &g_parser[ADJ_CFANF_LOW][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_CFANF_LOW},
	{"li_cfa_noise_filter.extent_fine_blue", &g_parser[ADJ_CFANF_LOW][0].argu[12 * 4], MAP_TO_S32, 1, ADJ_CFANF_LOW},
	{"li_cfa_noise_filter.extent_fine_green", &g_parser[ADJ_CFANF_LOW][0].argu[11 * 4], MAP_TO_S32, 1, ADJ_CFANF_LOW},
	{"li_cfa_noise_filter.extent_fine_red", &g_parser[ADJ_CFANF_LOW][0].argu[10 * 4], MAP_TO_S32, 1, ADJ_CFANF_LOW},
	{"li_cfa_noise_filter.extent_regular_blue", &g_parser[ADJ_CFANF_LOW][0].argu[9 * 4], MAP_TO_S32, 1, ADJ_CFANF_LOW},
	{"li_cfa_noise_filter.extent_regular_green", &g_parser[ADJ_CFANF_LOW][0].argu[8 * 4], MAP_TO_S32, 1, ADJ_CFANF_LOW},
	{"li_cfa_noise_filter.extent_regular_red", &g_parser[ADJ_CFANF_LOW][0].argu[7 * 4], MAP_TO_S32, 1, ADJ_CFANF_LOW},
	{"li_cfa_noise_filter.noise_level_blue", &g_parser[ADJ_CFANF_LOW][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_CFANF_LOW},
	{"li_cfa_noise_filter.noise_level_green", &g_parser[ADJ_CFANF_LOW][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_CFANF_LOW},
	{"li_cfa_noise_filter.noise_level_red", &g_parser[ADJ_CFANF_LOW][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_CFANF_LOW},
	{"li_cfa_noise_filter.original_blend_strength_blue", &g_parser[ADJ_CFANF_LOW][0].argu[6 * 4], MAP_TO_S32, 1, ADJ_CFANF_LOW},
	{"li_cfa_noise_filter.original_blend_strength_green", &g_parser[ADJ_CFANF_LOW][0].argu[5 * 4], MAP_TO_S32, 1, ADJ_CFANF_LOW},
	{"li_cfa_noise_filter.original_blend_strength_red", &g_parser[ADJ_CFANF_LOW][0].argu[4 * 4], MAP_TO_S32, 1, ADJ_CFANF_LOW},
	{"li_cfa_noise_filter.selectivity_fine", &g_parser[ADJ_CFANF_LOW][0].argu[17 * 4], MAP_TO_S32, 1, ADJ_CFANF_LOW},
	{"li_cfa_noise_filter.selectivity_regular", &g_parser[ADJ_CFANF_LOW][0].argu[16 * 4], MAP_TO_S32, 1, ADJ_CFANF_LOW},
	{"li_cfa_noise_filter.strength_fine_blue", &g_parser[ADJ_CFANF_LOW][0].argu[15 * 4], MAP_TO_S32, 1, ADJ_CFANF_LOW},
	{"li_cfa_noise_filter.strength_fine_green", &g_parser[ADJ_CFANF_LOW][0].argu[14 * 4], MAP_TO_S32, 1, ADJ_CFANF_LOW},
	{"li_cfa_noise_filter.strength_fine_red", &g_parser[ADJ_CFANF_LOW][0].argu[13 * 4], MAP_TO_S32, 1, ADJ_CFANF_LOW},

	/* ADJ_CFANF_HIGH */

	/* ADJ_LE */
	{"local_exposure.enable", &g_parser[ADJ_LE][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_LE},
	{"local_exposure.gain_curve", &g_parser[ADJ_LE][1].argu[0 * 4], MAP_TO_U16, TONE_CURVE_SIZE, ADJ_LE},
	{"local_exposure.luma_weight_blue", &g_parser[ADJ_LE][0].argu[5 * 4], MAP_TO_S32, 1, ADJ_LE},
	{"local_exposure.luma_weight_green", &g_parser[ADJ_LE][0].argu[4 * 4], MAP_TO_S32, 1, ADJ_LE},
	{"local_exposure.luma_weight_red", &g_parser[ADJ_LE][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_LE},
	{"local_exposure.luma_weight_shift", &g_parser[ADJ_LE][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_LE},
	{"local_exposure.radius", &g_parser[ADJ_LE][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_LE},

	/* ADJ_DEMOSAIC */
	{"li_demosaic.activity_difference_thresh", &g_parser[ADJ_DEMOSAIC][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_DEMOSAIC},
	{"li_demosaic.activity_thresh", &g_parser[ADJ_DEMOSAIC][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_DEMOSAIC},
	{"li_demosaic.grad_clip_thresh", &g_parser[ADJ_DEMOSAIC][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_DEMOSAIC},
	{"li_demosaic.grad_noise_thresh", &g_parser[ADJ_DEMOSAIC][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_DEMOSAIC},

	/* ADJ_CC */

	/* ADJ_TONE */
	{"tone_curve.curve_blue", &g_parser[ADJ_TONE][3].argu[0], MAP_TO_U16, TONE_CURVE_SIZE, ADJ_TONE},
	{"tone_curve.curve_red", &g_parser[ADJ_TONE][1].argu[0], MAP_TO_U16, TONE_CURVE_SIZE, ADJ_TONE},
	{"tone_curve.curve_green", &g_parser[ADJ_TONE][2].argu[0], MAP_TO_U16, TONE_CURVE_SIZE ,ADJ_TONE},

	/* ADJ_RGB2YUV */
	{"rgb_to_yuv_matrix.m11", &g_parser[ADJ_RGB2YUV][1].argu[0 * 2], MAP_TO_S16, 1, ADJ_RGB2YUV},
	{"rgb_to_yuv_matrix.m12", &g_parser[ADJ_RGB2YUV][1].argu[1 * 2], MAP_TO_S16, 1, ADJ_RGB2YUV},
	{"rgb_to_yuv_matrix.m13", &g_parser[ADJ_RGB2YUV][1].argu[2 * 2], MAP_TO_S16, 1, ADJ_RGB2YUV},
	{"rgb_to_yuv_matrix.m21", &g_parser[ADJ_RGB2YUV][1].argu[3 * 2], MAP_TO_S16, 1, ADJ_RGB2YUV},
	{"rgb_to_yuv_matrix.m22", &g_parser[ADJ_RGB2YUV][1].argu[4 * 2], MAP_TO_S16, 1, ADJ_RGB2YUV},
	{"rgb_to_yuv_matrix.m23", &g_parser[ADJ_RGB2YUV][1].argu[5 * 2], MAP_TO_S16, 1, ADJ_RGB2YUV},
	{"rgb_to_yuv_matrix.m31", &g_parser[ADJ_RGB2YUV][1].argu[6 * 2], MAP_TO_S16, 1, ADJ_RGB2YUV},
	{"rgb_to_yuv_matrix.m32", &g_parser[ADJ_RGB2YUV][1].argu[7 * 2], MAP_TO_S16, 1, ADJ_RGB2YUV},
	{"rgb_to_yuv_matrix.m33", &g_parser[ADJ_RGB2YUV][1].argu[8 * 2], MAP_TO_S16, 1, ADJ_RGB2YUV},
	{"rgb_to_yuv_matrix.u_offset", &g_parser[ADJ_RGB2YUV][1].argu[10 * 2], MAP_TO_S16, 1, ADJ_RGB2YUV},
	{"rgb_to_yuv_matrix.v_offset", &g_parser[ADJ_RGB2YUV][1].argu[11 * 2], MAP_TO_S16, 1, ADJ_RGB2YUV},
	{"rgb_to_yuv_matrix.y_offset", &g_parser[ADJ_RGB2YUV][1].argu[9 * 2], MAP_TO_S16, 1, ADJ_RGB2YUV},

	/* ADJ_CHROMA_SCALE */
	{"chroma_scale.enable", &g_parser[ADJ_CHROMA_SCALE][0].argu[0], MAP_TO_S32, 1, ADJ_CHROMA_SCALE},
	{"chroma_scale.gain_curve", &g_parser[ADJ_CHROMA_SCALE][1].argu[0], MAP_TO_U16, 128, ADJ_CHROMA_SCALE},

	/* ADJ_CHROMA_MEDIAN */
	{"li_chroma_median_filter.cb_adaptive_amount", &g_parser[ADJ_CHROMA_MEDIAN][0].argu[5 * 4], MAP_TO_S32, 1, ADJ_CHROMA_MEDIAN},
	{"li_chroma_median_filter.cb_adaptive_strength", &g_parser[ADJ_CHROMA_MEDIAN][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_CHROMA_MEDIAN},
	{"li_chroma_median_filter.cb_non_adaptive_strength", &g_parser[ADJ_CHROMA_MEDIAN][0].argu[3 * 4], MAP_TO_S32, 10, ADJ_CHROMA_MEDIAN},
	{"li_chroma_median_filter.cr_adaptive_amount", &g_parser[ADJ_CHROMA_MEDIAN][0].argu[6 * 4], MAP_TO_S32, 1, ADJ_CHROMA_MEDIAN},
	{"li_chroma_median_filter.cr_adaptive_strength", &g_parser[ADJ_CHROMA_MEDIAN][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_CHROMA_MEDIAN},
	{"li_chroma_median_filter.cr_non_adaptive_strength", &g_parser[ADJ_CHROMA_MEDIAN][0].argu[4 * 4], MAP_TO_S32, 1, ADJ_CHROMA_MEDIAN},
	{"li_chroma_median_filter.enable", &g_parser[ADJ_CHROMA_MEDIAN][0].argu[0], MAP_TO_S32, 1, ADJ_CHROMA_MEDIAN},

	/* ADJ_1STMODE_SEL */
	{"li_processing_select.advanced_features_enable", &g_parser[ADJ_1STMODE_SEL][0].argu[0], MAP_TO_S32, 1, ADJ_1STMODE_SEL},
	{"li_processing_select.use_1st_sharpen_not_asf", &g_parser[ADJ_1STMODE_SEL][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_1STMODE_SEL},

	/* ADJ_ASF  no e_th:4 */
	{"li_advanced_spatial_filter.T0T1_div_high", &g_parser[ADJ_ASF][0].argu[27 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.T0T1_div_high_delta", &g_parser[ADJ_ASF][0].argu[28 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.T0T1_div_high_strength", &g_parser[ADJ_ASF][0].argu[29 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.T0T1_div_low", &g_parser[ADJ_ASF][0].argu[23 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.T0T1_div_low_delta", &g_parser[ADJ_ASF][0].argu[24 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.T0T1_div_low_strength", &g_parser[ADJ_ASF][0].argu[25 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.T0T1_div_mid_strength", &g_parser[ADJ_ASF][0].argu[26 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.T0_down", &g_parser[ADJ_ASF][0].argu[14 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.T0_up", &g_parser[ADJ_ASF][0].argu[10 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.T1_down", &g_parser[ADJ_ASF][0].argu[15 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.T1_up", &g_parser[ADJ_ASF][0].argu[11 * 4], MAP_TO_S32, 1, ADJ_ASF},
//	{"li_advanced_spatial_filter.T1_up", NULL, MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.alpha_max_down", &g_parser[ADJ_ASF][0].argu[13 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.alpha_max_up", &g_parser[ADJ_ASF][0].argu[9 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.alpha_min_down", &g_parser[ADJ_ASF][0].argu[12 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.alpha_min_up", &g_parser[ADJ_ASF][0].argu[8 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.directional_decide_t0", &g_parser[ADJ_ASF][0].argu[6 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.directional_decide_t1", &g_parser[ADJ_ASF][0].argu[7 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.enable", &g_parser[ADJ_ASF][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.fir_specify", &g_parser[ADJ_ASF][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.fir_strength_dir", &g_parser[ADJ_ASF][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.fir_strength_iso", &g_parser[ADJ_ASF][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.fir_wide_edge_detect", &g_parser[ADJ_ASF][0].argu[5 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.level_str_adjust_high", &g_parser[ADJ_ASF][0].argu[20 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.level_str_adjust_high_delta", &g_parser[ADJ_ASF][0].argu[21 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.level_str_adjust_high_strength", &g_parser[ADJ_ASF][0].argu[22 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.level_str_adjust_low", &g_parser[ADJ_ASF][0].argu[16 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.level_str_adjust_low_delta", &g_parser[ADJ_ASF][0].argu[17 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.level_str_adjust_low_strength", &g_parser[ADJ_ASF][0].argu[18 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.level_str_adjust_mid_strength", &g_parser[ADJ_ASF][0].argu[19 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.max_change_down", &g_parser[ADJ_ASF][0].argu[32 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.max_change_not_T0T1_alpha", &g_parser[ADJ_ASF][0].argu[30 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.max_change_up", &g_parser[ADJ_ASF][0].argu[31 * 4], MAP_TO_S32, 1, ADJ_ASF},
	{"li_advanced_spatial_filter.fir_coefs", &g_parser[ADJ_ASF][4].argu[0 * 4], MAP_TO_S16, 9 * 25, ADJ_ASF},
	{"li_advanced_spatial_filter.fir_per_dir_fir_dir_amounts", &g_parser[ADJ_ASF][3].argu[0 * 4], MAP_TO_U16, 9, ADJ_ASF},
	{"li_advanced_spatial_filter.fir_per_dir_fir_dir_strengths", &g_parser[ADJ_ASF][2].argu[0 * 4], MAP_TO_U16, 9, ADJ_ASF},
	{"li_advanced_spatial_filter.fir_per_dir_fir_iso_strengths", &g_parser[ADJ_ASF][1].argu[0 * 4], MAP_TO_U16, 9, ADJ_ASF},

	/* ADJ_1ST_SHPBOTH */
	{"li_sharpen_noise_filter_both.edge_thresh", &g_parser[ADJ_1ST_SHPBOTH][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPBOTH},
	{"li_sharpen_noise_filter_both.enable", &g_parser[ADJ_1ST_SHPBOTH][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPBOTH},
	{"li_sharpen_noise_filter_both.max_change_down5x5", &g_parser[ADJ_1ST_SHPBOTH][0].argu[5 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPBOTH},
	{"li_sharpen_noise_filter_both.max_change_up5x5", &g_parser[ADJ_1ST_SHPBOTH][0].argu[4 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPBOTH},
	{"li_sharpen_noise_filter_both.mode", &g_parser[ADJ_1ST_SHPBOTH][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPBOTH},
	{"li_sharpen_noise_filter_both.wide_edge_detect", &g_parser[ADJ_1ST_SHPBOTH][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPBOTH},

	/* ADJ_1ST_SHPNOISE  No EdgeTresh:5, WideEdgeDetect:6 */
	{"li_sharpen_noise_filter_noise.T0", &g_parser[ADJ_1ST_SHPNOISE][0].argu[15 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPNOISE},
	{"li_sharpen_noise_filter_noise.T1", &g_parser[ADJ_1ST_SHPNOISE][0].argu[16 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPNOISE},
	{"li_sharpen_noise_filter_noise.alpha_max", &g_parser[ADJ_1ST_SHPNOISE][0].argu[18 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPNOISE},
	{"li_sharpen_noise_filter_noise.alpha_min", &g_parser[ADJ_1ST_SHPNOISE][0].argu[17 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPNOISE},
	{"li_sharpen_noise_filter_noise.fir_coefs", &g_parser[ADJ_1ST_SHPNOISE][4].argu[0], MAP_TO_S16, 9 * 25, ADJ_1ST_SHPNOISE},
	{"li_sharpen_noise_filter_noise.fir_per_dir_fir_dir_amounts", &g_parser[ADJ_1ST_SHPNOISE][3].argu[0], MAP_TO_U16, 9, ADJ_1ST_SHPNOISE},
	{"li_sharpen_noise_filter_noise.fir_per_dir_fir_dir_strengths", &g_parser[ADJ_1ST_SHPNOISE][2].argu[0], MAP_TO_U16, 9, ADJ_1ST_SHPNOISE},
	{"li_sharpen_noise_filter_noise.fir_per_dir_fir_iso_strengths", &g_parser[ADJ_1ST_SHPNOISE][1].argu[0], MAP_TO_U16, 9, ADJ_1ST_SHPNOISE},
	{"li_sharpen_noise_filter_noise.fir_specify", &g_parser[ADJ_1ST_SHPNOISE][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPNOISE},

	{"li_sharpen_noise_filter_noise.fir_strength_dir", &g_parser[ADJ_1ST_SHPNOISE][0].argu[4 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPNOISE},
	{"li_sharpen_noise_filter_noise.fir_strength_iso", &g_parser[ADJ_1ST_SHPNOISE][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPNOISE},
	{"li_sharpen_noise_filter_noise.level_str_adjust_high", &g_parser[ADJ_1ST_SHPNOISE][0].argu[11 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPNOISE},
	{"li_sharpen_noise_filter_noise.level_str_adjust_high_delta", &g_parser[ADJ_1ST_SHPNOISE][0].argu[12 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPNOISE},
	{"li_sharpen_noise_filter_noise.level_str_adjust_high_strength", &g_parser[ADJ_1ST_SHPNOISE][0].argu[13 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPNOISE},
	{"li_sharpen_noise_filter_noise.level_str_adjust_low", &g_parser[ADJ_1ST_SHPNOISE][0].argu[7 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPNOISE},
	{"li_sharpen_noise_filter_noise.level_str_adjust_low_delta", &g_parser[ADJ_1ST_SHPNOISE][0].argu[8 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPNOISE},
	{"li_sharpen_noise_filter_noise.level_str_adjust_low_strength", &g_parser[ADJ_1ST_SHPNOISE][0].argu[9 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPNOISE},
	{"li_sharpen_noise_filter_noise.level_str_adjust_mid_strength", &g_parser[ADJ_1ST_SHPNOISE][0].argu[10 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPNOISE},
	{"li_sharpen_noise_filter_noise.level_str_adjust_not_T0T1_level_based", &g_parser[ADJ_1ST_SHPNOISE][0].argu[14 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPNOISE},
	{"li_sharpen_noise_filter_noise.max_change_down", &g_parser[ADJ_1ST_SHPNOISE][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPNOISE},
	{"li_sharpen_noise_filter_noise.max_change_up", &g_parser[ADJ_1ST_SHPNOISE][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPNOISE},

	/* ADJ_1ST_SHPFIR No EdgeThresh:3,  WideEdgeDetect:4 */
	{"li_sharpen_noise_filter_sharpen.fir_coefs", &g_parser[ADJ_1ST_SHPFIR][4].argu[0], MAP_TO_S16, 9 * 25, ADJ_1ST_SHPFIR},
	{"li_sharpen_noise_filter_sharpen.fir_per_dir_fir_dir_amounts", &g_parser[ADJ_1ST_SHPFIR][3].argu[0], MAP_TO_U16, 9, ADJ_1ST_SHPFIR},
	{"li_sharpen_noise_filter_sharpen.fir_per_dir_fir_dir_strengths", &g_parser[ADJ_1ST_SHPFIR][2].argu[0], MAP_TO_U16, 9, ADJ_1ST_SHPFIR},
	{"li_sharpen_noise_filter_sharpen.fir_per_dir_fir_iso_strengths", &g_parser[ADJ_1ST_SHPFIR][1].argu[0], MAP_TO_U16, 9, ADJ_1ST_SHPFIR},
	{"li_sharpen_noise_filter_sharpen.fir_specify", &g_parser[ADJ_1ST_SHPFIR][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPFIR},
	{"li_sharpen_noise_filter_sharpen.fir_strength_dir", &g_parser[ADJ_1ST_SHPFIR][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPFIR},
	{"li_sharpen_noise_filter_sharpen.fir_strength_iso", &g_parser[ADJ_1ST_SHPFIR][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPFIR},

	/* ADJ_1ST_SHPCORING  No fractional_bits */
	{"li_sharpen_noise_filter_sharpen_coring.coring_table", &g_parser[ADJ_1ST_SHPCORING][1].argu[0], MAP_TO_U8, TONE_CURVE_SIZE, ADJ_1ST_SHPCORING},
	{"li_sharpen_noise_filter_sharpen_coring.fractional_bits", NULL, MAP_TO_S32, 1, ADJ_1ST_SHPCORING},

	/* ADJ_1ST_SHPCORING_INDEX_SCALE */
	{"li_sharpen_noise_filter_sharpen_coring_index_scale.high", &g_parser[ADJ_1ST_SHPCORING_INDEX_SCALE][0].argu[4 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPCORING_INDEX_SCALE},
	{"li_sharpen_noise_filter_sharpen_coring_index_scale.high_delta", &g_parser[ADJ_1ST_SHPCORING_INDEX_SCALE][0].argu[5 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPCORING_INDEX_SCALE},
	{"li_sharpen_noise_filter_sharpen_coring_index_scale.high_strength", &g_parser[ADJ_1ST_SHPCORING_INDEX_SCALE][0].argu[6 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPCORING_INDEX_SCALE},
	{"li_sharpen_noise_filter_sharpen_coring_index_scale.low", &g_parser[ADJ_1ST_SHPCORING_INDEX_SCALE][0].argu[0], MAP_TO_S32, 1, ADJ_1ST_SHPCORING_INDEX_SCALE},
	{"li_sharpen_noise_filter_sharpen_coring_index_scale.low_delta", &g_parser[ADJ_1ST_SHPCORING_INDEX_SCALE][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPCORING_INDEX_SCALE},
	{"li_sharpen_noise_filter_sharpen_coring_index_scale.low_strength", &g_parser[ADJ_1ST_SHPCORING_INDEX_SCALE][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPCORING_INDEX_SCALE},
	{"li_sharpen_noise_filter_sharpen_coring_index_scale.mid_strength", &g_parser[ADJ_1ST_SHPCORING_INDEX_SCALE][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPCORING_INDEX_SCALE},

	/* ADJ_1ST_SHPCORING_MIN_RESULT */
	{"li_sharpen_noise_filter_sharpen_min_coring_result.high", &g_parser[ADJ_1ST_SHPCORING_MIN_RESULT][0].argu[4 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPCORING_MIN_RESULT},
	{"li_sharpen_noise_filter_sharpen_min_coring_result.high_delta", &g_parser[ADJ_1ST_SHPCORING_MIN_RESULT][0].argu[5 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPCORING_MIN_RESULT},
	{"li_sharpen_noise_filter_sharpen_min_coring_result.high_strength", &g_parser[ADJ_1ST_SHPCORING_MIN_RESULT][0].argu[6 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPCORING_MIN_RESULT},
	{"li_sharpen_noise_filter_sharpen_min_coring_result.low", &g_parser[ADJ_1ST_SHPCORING_MIN_RESULT][0].argu[0], MAP_TO_S32, 1, ADJ_1ST_SHPCORING_MIN_RESULT},
	{"li_sharpen_noise_filter_sharpen_min_coring_result.low_delta", &g_parser[ADJ_1ST_SHPCORING_MIN_RESULT][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPCORING_MIN_RESULT},
	{"li_sharpen_noise_filter_sharpen_min_coring_result.low_strength", &g_parser[ADJ_1ST_SHPCORING_MIN_RESULT][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPCORING_MIN_RESULT},
	{"li_sharpen_noise_filter_sharpen_min_coring_result.mid_strength", &g_parser[ADJ_1ST_SHPCORING_MIN_RESULT][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPCORING_MIN_RESULT},

	/* ADJ_1ST_SHPCORING_SCALE_CORING */
	{"li_sharpen_noise_filter_sharpen_scale_coring.high", &g_parser[ADJ_1ST_SHPCORING_SCALE_CORING][0].argu[4 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPCORING_SCALE_CORING},
	{"li_sharpen_noise_filter_sharpen_scale_coring.high_delta", &g_parser[ADJ_1ST_SHPCORING_SCALE_CORING][0].argu[5 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPCORING_SCALE_CORING},
	{"li_sharpen_noise_filter_sharpen_scale_coring.high_strength", &g_parser[ADJ_1ST_SHPCORING_SCALE_CORING][0].argu[6 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPCORING_SCALE_CORING},
	{"li_sharpen_noise_filter_sharpen_scale_coring.low", &g_parser[ADJ_1ST_SHPCORING_SCALE_CORING][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPCORING_SCALE_CORING},
	{"li_sharpen_noise_filter_sharpen_scale_coring.low_delta", &g_parser[ADJ_1ST_SHPCORING_SCALE_CORING][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPCORING_SCALE_CORING},
	{"li_sharpen_noise_filter_sharpen_scale_coring.low_strength", &g_parser[ADJ_1ST_SHPCORING_SCALE_CORING][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPCORING_SCALE_CORING},
	{"li_sharpen_noise_filter_sharpen_scale_coring.mid_strength", &g_parser[ADJ_1ST_SHPCORING_SCALE_CORING][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_1ST_SHPCORING_SCALE_CORING},

	/* ADJ_VIDEO_MCTF */
	{"video_mctf.T0", &g_parser[ADJ_VIDEO_MCTF][0].argu[5 * 4], MAP_TO_S32, 4, ADJ_VIDEO_MCTF},
	{"video_mctf.T1", &g_parser[ADJ_VIDEO_MCTF][0].argu[5 * 4 + 4 * 4], MAP_TO_S32, 4, ADJ_VIDEO_MCTF},
	{"video_mctf.T2", &g_parser[ADJ_VIDEO_MCTF][0].argu[5 * 4 + 4 * 4 * 2], MAP_TO_S32, 4, ADJ_VIDEO_MCTF},
	{"video_mctf.T3", &g_parser[ADJ_VIDEO_MCTF][0].argu[5 * 4 + 4 * 4 * 3], MAP_TO_S32, 4, ADJ_VIDEO_MCTF},
	{"video_mctf.alpha1", &g_parser[ADJ_VIDEO_MCTF][0].argu[5 * 4 + 4 * 4 * 4], MAP_TO_S32, 4, ADJ_VIDEO_MCTF},
	{"video_mctf.alpha2", &g_parser[ADJ_VIDEO_MCTF][0].argu[5 * 4 + 4 * 4 * 5], MAP_TO_S32, 4, ADJ_VIDEO_MCTF},
	{"video_mctf.alpha3", &g_parser[ADJ_VIDEO_MCTF][0].argu[5 * 4 + 4 * 4 * 6], MAP_TO_S32, 4, ADJ_VIDEO_MCTF},
	{"video_mctf.enable", &g_parser[ADJ_VIDEO_MCTF][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_VIDEO_MCTF},
	{"video_mctf.u_max_change", &g_parser[ADJ_VIDEO_MCTF][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_VIDEO_MCTF},
	{"video_mctf.v_max_change", &g_parser[ADJ_VIDEO_MCTF][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_VIDEO_MCTF},
	{"video_mctf.weighting_based_on_local_motion", &g_parser[ADJ_VIDEO_MCTF][0].argu[4 * 4], MAP_TO_S32, 1, ADJ_VIDEO_MCTF},
	{"video_mctf.y_max_change", &g_parser[ADJ_VIDEO_MCTF][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_VIDEO_MCTF},

	/* ADJ_HDR_ALPHA */
	/* ADJ_HDR_THRESHOLD */
	/* ADJ_HDR_CE */

	/* ADJ_CHROMANF */
	{"li_chroma_filter.enable", &g_parser[ADJ_CHROMANF][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_CHROMANF},
	{"li_chroma_filter.noise_level_cb", &g_parser[ADJ_CHROMANF][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_CHROMANF},
	{"li_chroma_filter.noise_level_cr", &g_parser[ADJ_CHROMANF][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_CHROMANF},
	{"li_chroma_filter.original_blend_strength_cb", &g_parser[ADJ_CHROMANF][0].argu[3 * 4], MAP_TO_S32, 1, INVALID_CONTAINER_ID},
	{"li_chroma_filter.original_blend_strength_cr", &g_parser[ADJ_CHROMANF][0].argu[4 * 4], MAP_TO_S32, 1, ADJ_CHROMANF},
	{"li_chroma_filter.radius", &g_parser[ADJ_CHROMANF][0].argu[5 * 4], MAP_TO_S32, 1, ADJ_CHROMANF},

	/* ADJ_TEMPORAL_ADJUST */
	{"video_mctf_temporal_adjust.enable", &g_parser[ADJ_TEMPORAL_ADJUST][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_TEMPORAL_ADJUST},
	{"video_mctf_temporal_adjust.frames_combine_thresh", &g_parser[ADJ_TEMPORAL_ADJUST][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_TEMPORAL_ADJUST},
	{"video_mctf_temporal_adjust.min", &g_parser[ADJ_TEMPORAL_ADJUST][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_TEMPORAL_ADJUST},
	{"video_mctf_temporal_adjust.motion_detection_delay", &g_parser[ADJ_TEMPORAL_ADJUST][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_TEMPORAL_ADJUST},
	{"video_mctf_temporal_adjust.mul", &g_parser[ADJ_TEMPORAL_ADJUST][0].argu[4 * 4], MAP_TO_S32, 1, ADJ_TEMPORAL_ADJUST},
	{"video_mctf_temporal_adjust.sub", &g_parser[ADJ_TEMPORAL_ADJUST][0].argu[5 * 4], MAP_TO_S32, 1, ADJ_TEMPORAL_ADJUST},
	{"video_mctf_temporal_adjust.smooth_detection", &g_parser[ADJ_TEMPORAL_ADJUST][0].argu[6 * 4], MAP_TO_S32, 1, ADJ_TEMPORAL_ADJUST},
	{"video_mctf_temporal_adjust.motion_detect_dc_map_high", &g_parser[ADJ_TEMPORAL_ADJUST][0].argu[7 * 4], MAP_TO_S32, 1, ADJ_TEMPORAL_ADJUST},
	{"video_mctf_temporal_adjust.motion_detect_dc_map_high_delta", &g_parser[ADJ_TEMPORAL_ADJUST][0].argu[8 * 4], MAP_TO_S32, 1, ADJ_TEMPORAL_ADJUST},
	{"video_mctf_temporal_adjust.motion_detect_dc_map_high_strength", &g_parser[ADJ_TEMPORAL_ADJUST][0].argu[9 * 4], MAP_TO_S32, 1, ADJ_TEMPORAL_ADJUST},
	{"video_mctf_temporal_adjust.motion_detect_dc_map_low", &g_parser[ADJ_TEMPORAL_ADJUST][0].argu[10 * 4], MAP_TO_S32, 1, ADJ_TEMPORAL_ADJUST},
	{"video_mctf_temporal_adjust.motion_detect_dc_map_low_delta", &g_parser[ADJ_TEMPORAL_ADJUST][0].argu[11 * 4], MAP_TO_S32, 1, ADJ_TEMPORAL_ADJUST},
	{"video_mctf_temporal_adjust.motion_detect_dc_map_low_strength", &g_parser[ADJ_TEMPORAL_ADJUST][0].argu[12 * 4], MAP_TO_S32, 1, ADJ_TEMPORAL_ADJUST},
	{"video_mctf_temporal_adjust.motion_detect_dc_map_mid_strength", &g_parser[ADJ_TEMPORAL_ADJUST][0].argu[13 * 4], MAP_TO_S32, 1, ADJ_TEMPORAL_ADJUST},
	{"video_mctf_temporal_adjust.motion_detection_delay2", &g_parser[ADJ_TEMPORAL_ADJUST][0].argu[14 * 4], MAP_TO_S32, 1, ADJ_TEMPORAL_ADJUST},
	{"video_mctf_temporal_adjust.y_max", &g_parser[ADJ_TEMPORAL_ADJUST][0].argu[15 * 4], MAP_TO_S32, 1, ADJ_TEMPORAL_ADJUST},
	{"video_mctf_temporal_adjust.y_min", &g_parser[ADJ_TEMPORAL_ADJUST][0].argu[16 * 4], MAP_TO_S32, 1, ADJ_TEMPORAL_ADJUST},
	{"video_mctf_temporal_adjust.uv_max", &g_parser[ADJ_TEMPORAL_ADJUST][0].argu[17 * 4], MAP_TO_S32, 1, ADJ_TEMPORAL_ADJUST},
	{"video_mctf_temporal_adjust.uv_min", &g_parser[ADJ_TEMPORAL_ADJUST][0].argu[18 * 4], MAP_TO_S32, 1, ADJ_TEMPORAL_ADJUST},

	/* ADJ_FINAL_SHPBOTH */
	{"li_final_sharpen_noise_filter_both.edge_thresh", &g_parser[ADJ_FINAL_SHPBOTH][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPBOTH},
	{"li_final_sharpen_noise_filter_both.enable", &g_parser[ADJ_FINAL_SHPBOTH][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPBOTH},
	{"li_final_sharpen_noise_filter_both.max_change_down5x5", &g_parser[ADJ_FINAL_SHPBOTH][0].argu[5 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPBOTH},
	{"li_final_sharpen_noise_filter_both.max_change_up5x5", &g_parser[ADJ_FINAL_SHPBOTH][0].argu[4 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPBOTH},
	{"li_final_sharpen_noise_filter_both.mode", &g_parser[ADJ_FINAL_SHPBOTH][0].argu[1 * 4], MAP_TO_S32, 1, INVALID_CONTAINER_ID},
	{"li_final_sharpen_noise_filter_both.wide_edge_detect", &g_parser[ADJ_FINAL_SHPBOTH][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPBOTH},

	/* ADJ_FINAL_SHPNOISE No EdgeTresh:5, WideEdgeDetect:6*/
	{"li_final_sharpen_noise_filter_noise.T0", &g_parser[ADJ_FINAL_SHPNOISE][0].argu[15 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPNOISE},
	{"li_final_sharpen_noise_filter_noise.T1", &g_parser[ADJ_FINAL_SHPNOISE][0].argu[16 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPNOISE},
	{"li_final_sharpen_noise_filter_noise.alpha_max", &g_parser[ADJ_FINAL_SHPNOISE][0].argu[18 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPNOISE},
	{"li_final_sharpen_noise_filter_noise.alpha_min", &g_parser[ADJ_FINAL_SHPNOISE][0].argu[17 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPNOISE},
	{"li_final_sharpen_noise_filter_noise.fir_coefs", &g_parser[ADJ_FINAL_SHPNOISE][4].argu[0], MAP_TO_S16, 9 * 25, ADJ_FINAL_SHPNOISE},
	{"li_final_sharpen_noise_filter_noise.fir_per_dir_fir_dir_amounts", &g_parser[ADJ_FINAL_SHPNOISE][3].argu[0], MAP_TO_U16, 9, ADJ_FINAL_SHPNOISE},
	{"li_final_sharpen_noise_filter_noise.fir_per_dir_fir_dir_strengths", &g_parser[ADJ_FINAL_SHPNOISE][2].argu[0], MAP_TO_U16, 9, INVALID_CONTAINER_ID},
	{"li_final_sharpen_noise_filter_noise.fir_per_dir_fir_iso_strengths", &g_parser[ADJ_FINAL_SHPNOISE][1].argu[0], MAP_TO_U16, 9, ADJ_FINAL_SHPNOISE},
	{"li_final_sharpen_noise_filter_noise.fir_specify", &g_parser[ADJ_FINAL_SHPNOISE][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPNOISE},
	{"li_final_sharpen_noise_filter_noise.fir_strength_dir", &g_parser[ADJ_FINAL_SHPNOISE][0].argu[4 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPNOISE},
	{"li_final_sharpen_noise_filter_noise.fir_strength_iso", &g_parser[ADJ_FINAL_SHPNOISE][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPNOISE},
	{"li_final_sharpen_noise_filter_noise.level_str_adjust_high", &g_parser[ADJ_FINAL_SHPNOISE][0].argu[11 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPNOISE},
	{"li_final_sharpen_noise_filter_noise.level_str_adjust_high_delta", &g_parser[ADJ_FINAL_SHPNOISE][0].argu[12 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPNOISE},
	{"li_final_sharpen_noise_filter_noise.level_str_adjust_high_strength", &g_parser[ADJ_FINAL_SHPNOISE][0].argu[13 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPNOISE},
	{"li_final_sharpen_noise_filter_noise.level_str_adjust_low", &g_parser[ADJ_FINAL_SHPNOISE][0].argu[7 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPNOISE},
	{"li_final_sharpen_noise_filter_noise.level_str_adjust_low_delta", &g_parser[ADJ_FINAL_SHPNOISE][0].argu[8 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPNOISE},
	{"li_final_sharpen_noise_filter_noise.level_str_adjust_low_strength", &g_parser[ADJ_FINAL_SHPNOISE][0].argu[9 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPNOISE},
	{"li_final_sharpen_noise_filter_noise.level_str_adjust_mid_strength", &g_parser[ADJ_FINAL_SHPNOISE][0].argu[10 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPNOISE},
	{"li_final_sharpen_noise_filter_noise.level_str_adjust_not_T0T1_level_based", &g_parser[ADJ_FINAL_SHPNOISE][0].argu[14 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPNOISE},
	{"li_final_sharpen_noise_filter_noise.max_change_down", &g_parser[ADJ_FINAL_SHPNOISE][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPNOISE},
	{"li_final_sharpen_noise_filter_noise.max_change_up", &g_parser[ADJ_FINAL_SHPNOISE][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPNOISE},

	/* ADJ_FINAL_SHPFIR	 No EdgeThresh:3,  WideEdgeDetect:4 */
	{"li_final_sharpen_noise_filter_sharpen.fir_coefs", &g_parser[ADJ_FINAL_SHPFIR][4].argu[0], MAP_TO_S16, 9 * 25, ADJ_FINAL_SHPFIR},
	{"li_final_sharpen_noise_filter_sharpen.fir_per_dir_fir_dir_amounts", &g_parser[ADJ_FINAL_SHPFIR][3].argu[0], MAP_TO_U16, 9, ADJ_FINAL_SHPFIR},
	{"li_final_sharpen_noise_filter_sharpen.fir_per_dir_fir_dir_strengths", &g_parser[ADJ_FINAL_SHPFIR][2].argu[0], MAP_TO_U16, 9, ADJ_FINAL_SHPFIR},
	{"li_final_sharpen_noise_filter_sharpen.fir_per_dir_fir_iso_strengths", &g_parser[ADJ_FINAL_SHPFIR][1].argu[0], MAP_TO_U16, 9, ADJ_FINAL_SHPFIR},
	{"li_final_sharpen_noise_filter_sharpen.fir_specify", &g_parser[ADJ_FINAL_SHPFIR][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPFIR},
	{"li_final_sharpen_noise_filter_sharpen.fir_strength_dir", &g_parser[ADJ_FINAL_SHPFIR][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPFIR},
	{"li_final_sharpen_noise_filter_sharpen.fir_strength_iso", &g_parser[ADJ_FINAL_SHPFIR][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPFIR},

	/* ADJ_FINAL_SHPCORING */
	{"li_final_sharpen_noise_filter_sharpen_coring.coring_table", &g_parser[ADJ_FINAL_SHPCORING][1].argu[0], MAP_TO_U8, TONE_CURVE_SIZE, ADJ_FINAL_SHPCORING},
	{"li_final_sharpen_noise_filter_sharpen_coring.fractional_bits", NULL, MAP_TO_S32, 1, ADJ_FINAL_SHPCORING},

	/* ADJ_FINAL_SHPCORING_INDEX_SCALE */
	{"li_final_sharpen_noise_filter_sharpen_coring_index_scale.high", &g_parser[ADJ_FINAL_SHPCORING_INDEX_SCALE][0].argu[4 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPCORING_INDEX_SCALE},
	{"li_final_sharpen_noise_filter_sharpen_coring_index_scale.high_delta", &g_parser[ADJ_FINAL_SHPCORING_INDEX_SCALE][0].argu[5 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPCORING_INDEX_SCALE},
	{"li_final_sharpen_noise_filter_sharpen_coring_index_scale.high_strength", &g_parser[ADJ_FINAL_SHPCORING_INDEX_SCALE][0].argu[6 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPCORING_INDEX_SCALE},
	{"li_final_sharpen_noise_filter_sharpen_coring_index_scale.low", &g_parser[ADJ_FINAL_SHPCORING_INDEX_SCALE][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPCORING_INDEX_SCALE},
	{"li_final_sharpen_noise_filter_sharpen_coring_index_scale.low_delta", &g_parser[ADJ_FINAL_SHPCORING_INDEX_SCALE][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPCORING_INDEX_SCALE},
	{"li_final_sharpen_noise_filter_sharpen_coring_index_scale.low_strength", &g_parser[ADJ_FINAL_SHPCORING_INDEX_SCALE][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPCORING_INDEX_SCALE},
	{"li_final_sharpen_noise_filter_sharpen_coring_index_scale.mid_strength", &g_parser[ADJ_FINAL_SHPCORING_INDEX_SCALE][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPCORING_INDEX_SCALE},

	/* ADJ_FINAL_SHPCORING_MIN_RESULT */
	{"li_final_sharpen_noise_filter_sharpen_min_coring_result.high", &g_parser[ADJ_FINAL_SHPCORING_MIN_RESULT][0].argu[4 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPCORING_MIN_RESULT},
	{"li_final_sharpen_noise_filter_sharpen_min_coring_result.high_delta", &g_parser[ADJ_FINAL_SHPCORING_MIN_RESULT][0].argu[5 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPCORING_MIN_RESULT},
	{"li_final_sharpen_noise_filter_sharpen_min_coring_result.high_strength", &g_parser[ADJ_FINAL_SHPCORING_MIN_RESULT][0].argu[6 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPCORING_MIN_RESULT},
	{"li_final_sharpen_noise_filter_sharpen_min_coring_result.low", &g_parser[ADJ_FINAL_SHPCORING_MIN_RESULT][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPCORING_MIN_RESULT},
	{"li_final_sharpen_noise_filter_sharpen_min_coring_result.low_delta", &g_parser[ADJ_FINAL_SHPCORING_MIN_RESULT][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPCORING_MIN_RESULT},
	{"li_final_sharpen_noise_filter_sharpen_min_coring_result.low_strength", &g_parser[ADJ_FINAL_SHPCORING_MIN_RESULT][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPCORING_MIN_RESULT},
	{"li_final_sharpen_noise_filter_sharpen_min_coring_result.mid_strength", &g_parser[ADJ_FINAL_SHPCORING_MIN_RESULT][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPCORING_MIN_RESULT},

	/* ADJ_FINAL_SHPCORING_SCALE_CORING */
	{"li_final_sharpen_noise_filter_sharpen_scale_coring.high", &g_parser[ADJ_FINAL_SHPCORING_SCALE_CORING][0].argu[4 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPCORING_SCALE_CORING},
	{"li_final_sharpen_noise_filter_sharpen_scale_coring.high_delta", &g_parser[ADJ_FINAL_SHPCORING_SCALE_CORING][0].argu[5 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPCORING_SCALE_CORING},
	{"li_final_sharpen_noise_filter_sharpen_scale_coring.high_strength", &g_parser[ADJ_FINAL_SHPCORING_SCALE_CORING][0].argu[6 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPCORING_SCALE_CORING},
	{"li_final_sharpen_noise_filter_sharpen_scale_coring.low", &g_parser[ADJ_FINAL_SHPCORING_SCALE_CORING][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPCORING_SCALE_CORING},
	{"li_final_sharpen_noise_filter_sharpen_scale_coring.low_delta", &g_parser[ADJ_FINAL_SHPCORING_SCALE_CORING][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPCORING_SCALE_CORING},
	{"li_final_sharpen_noise_filter_sharpen_scale_coring.low_strength", &g_parser[ADJ_FINAL_SHPCORING_SCALE_CORING][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPCORING_SCALE_CORING},
	{"li_final_sharpen_noise_filter_sharpen_scale_coring.mid_strength", &g_parser[ADJ_FINAL_SHPCORING_SCALE_CORING][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_FINAL_SHPCORING_SCALE_CORING},

	/* ADJ_WIDE_CHROMA_FILTER */
	/* ADJ_WIDE_CHROMA_FILTER_COMBINE */

	/* ADJ_MO_ANTIALIASING */
	{"mo_anti_aliasing.enable", &g_parser[ADJ_MO_ANTIALIASING][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_MO_ANTIALIASING},
	{"mo_anti_aliasing.log_fractional_correct", &g_parser[ADJ_MO_ANTIALIASING][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_MO_ANTIALIASING},
	{"mo_anti_aliasing.thresh", &g_parser[ADJ_MO_ANTIALIASING][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_MO_ANTIALIASING},

	/* ADJ_MO_GRGB_MISMATCH */
	{"mo_gb_gr_mismatch_correct.narrow_enable", &g_parser[ADJ_MO_GRGB_MISMATCH][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_MO_GRGB_MISMATCH},
	{"mo_gb_gr_mismatch_correct.wide_enable", &g_parser[ADJ_MO_GRGB_MISMATCH][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_MO_GRGB_MISMATCH},
	{"mo_gb_gr_mismatch_correct.wide_safety", &g_parser[ADJ_MO_GRGB_MISMATCH][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_MO_GRGB_MISMATCH},
	{"mo_gb_gr_mismatch_correct.wide_thresh", &g_parser[ADJ_MO_GRGB_MISMATCH][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_MO_GRGB_MISMATCH},

	/* ADJ_MO_DPC */
	{"mo_auto_bad_pixel_correction.correction_method", &g_parser[ADJ_MO_DPC][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_MO_DPC},
	{"mo_auto_bad_pixel_correction.dark_pixel_detection_strength", &g_parser[ADJ_MO_DPC][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_MO_DPC},
	{"mo_auto_bad_pixel_correction.enable", &g_parser[ADJ_MO_DPC][0].argu[0 * 4], MAP_TO_S32, 1, INVALID_CONTAINER_ID},
	{"mo_auto_bad_pixel_correction.hot_pixel_detection_strength", &g_parser[ADJ_MO_DPC][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_MO_DPC},

	/* ADJ_MO_CFANF */
	{"mo_cfa_noise_filter.enable", &g_parser[ADJ_MO_CFANF][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_MO_CFANF},
	{"mo_cfa_noise_filter.extent_fine_blue", &g_parser[ADJ_MO_CFANF][0].argu[12 * 4], MAP_TO_S32, 1, ADJ_MO_CFANF},
	{"mo_cfa_noise_filter.extent_fine_green", &g_parser[ADJ_MO_CFANF][0].argu[11 * 4], MAP_TO_S32, 1, ADJ_MO_CFANF},
	{"mo_cfa_noise_filter.extent_fine_red", &g_parser[ADJ_MO_CFANF][0].argu[10 * 4], MAP_TO_S32, 1, ADJ_MO_CFANF},
	{"mo_cfa_noise_filter.extent_regular_blue", &g_parser[ADJ_MO_CFANF][0].argu[9 * 4], MAP_TO_S32, 1, ADJ_MO_CFANF},
	{"mo_cfa_noise_filter.extent_regular_green", &g_parser[ADJ_MO_CFANF][0].argu[8 * 4], MAP_TO_S32, 1, ADJ_MO_CFANF},
	{"mo_cfa_noise_filter.extent_regular_red", &g_parser[ADJ_MO_CFANF][0].argu[7 * 4], MAP_TO_S32, 1, ADJ_MO_CFANF},
	{"mo_cfa_noise_filter.noise_level_blue", &g_parser[ADJ_MO_CFANF][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_MO_CFANF},
	{"mo_cfa_noise_filter.noise_level_green", &g_parser[ADJ_MO_CFANF][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_MO_CFANF},
	{"mo_cfa_noise_filter.noise_level_red", &g_parser[ADJ_MO_CFANF][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_MO_CFANF},
	{"mo_cfa_noise_filter.original_blend_strength_blue", &g_parser[ADJ_MO_CFANF][0].argu[6 * 4], MAP_TO_S32, 1, INVALID_CONTAINER_ID},
	{"mo_cfa_noise_filter.original_blend_strength_green", &g_parser[ADJ_MO_CFANF][0].argu[5 * 4], MAP_TO_S32, 1, ADJ_MO_CFANF},
	{"mo_cfa_noise_filter.original_blend_strength_red", &g_parser[ADJ_MO_CFANF][0].argu[4 * 4], MAP_TO_S32, 1, ADJ_MO_CFANF},
	{"mo_cfa_noise_filter.selectivity_fine", &g_parser[ADJ_MO_CFANF][0].argu[17 * 4], MAP_TO_S32, 1, ADJ_MO_CFANF},
	{"mo_cfa_noise_filter.selectivity_regular", &g_parser[ADJ_MO_CFANF][0].argu[16 * 4], MAP_TO_S32, 1, ADJ_MO_CFANF},
	{"mo_cfa_noise_filter.strength_fine_blue", &g_parser[ADJ_MO_CFANF][0].argu[15 * 4], MAP_TO_S32, 1, ADJ_MO_CFANF},
	{"mo_cfa_noise_filter.strength_fine_green", &g_parser[ADJ_MO_CFANF][0].argu[14 * 4], MAP_TO_S32, 1, ADJ_MO_CFANF},
	{"mo_cfa_noise_filter.strength_fine_red", &g_parser[ADJ_MO_CFANF][0].argu[13 * 4], MAP_TO_S32, 1, ADJ_MO_CFANF},

	/* ADJ_MO_DEMOSAIC */
	{"mo_demosaic.activity_difference_thresh", &g_parser[ADJ_MO_DEMOSAIC][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_MO_DEMOSAIC},
	{"mo_demosaic.activity_thresh", &g_parser[ADJ_MO_DEMOSAIC][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_MO_DEMOSAIC},
	{"mo_demosaic.grad_clip_thresh", &g_parser[ADJ_MO_DEMOSAIC][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_MO_DEMOSAIC},
	{"mo_demosaic.grad_noise_thresh", &g_parser[ADJ_MO_DEMOSAIC][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_MO_DEMOSAIC},

	/* ADJ_MO_CHROMA_MEDIAN */
	{"mo_chroma_median_filter.cb_adaptive_amount", &g_parser[ADJ_MO_DEMOSAIC][0].argu[5 * 4], MAP_TO_S32, 1, ADJ_MO_CHROMA_MEDIAN},
	{"mo_chroma_median_filter.cb_adaptive_strength", &g_parser[ADJ_MO_DEMOSAIC][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_MO_CHROMA_MEDIAN},
	{"mo_chroma_median_filter.cb_non_adaptive_strength", &g_parser[ADJ_MO_DEMOSAIC][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_MO_CHROMA_MEDIAN},
	{"mo_chroma_median_filter.cr_adaptive_amount", &g_parser[ADJ_MO_DEMOSAIC][0].argu[6 * 4], MAP_TO_S32, 1, INVALID_CONTAINER_ID},
	{"mo_chroma_median_filter.cr_adaptive_strength", &g_parser[ADJ_MO_DEMOSAIC][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_MO_CHROMA_MEDIAN},
	{"mo_chroma_median_filter.cr_non_adaptive_strength", &g_parser[ADJ_MO_DEMOSAIC][0].argu[4 * 4], MAP_TO_S32, 1, ADJ_MO_CHROMA_MEDIAN},
	{"mo_chroma_median_filter.enable", &g_parser[ADJ_MO_DEMOSAIC][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_MO_CHROMA_MEDIAN},

	/* ADJ_MO_CNF */
	{"mo_chroma_filter.enable", &g_parser[ADJ_MO_CNF][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_MO_CNF},
	{"mo_chroma_filter.noise_level_cb", &g_parser[ADJ_MO_CNF][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_MO_CNF},
	{"mo_chroma_filter.noise_level_cr", &g_parser[ADJ_MO_CNF][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_MO_CNF},
	{"mo_chroma_filter.original_blend_strength_cb", &g_parser[ADJ_MO_CNF][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_MO_CNF},
	{"mo_chroma_filter.original_blend_strength_cr", &g_parser[ADJ_MO_CNF][0].argu[4 * 4], MAP_TO_S32, 1, ADJ_MO_CNF},
	{"mo_chroma_filter.radius", &g_parser[ADJ_MO_CNF][0].argu[5 * 4], MAP_TO_S32, 1, ADJ_MO_CNF},

	/* ADJ_MO_1STMODE_SEL */
	{"mo_processing_select.use_1st_sharpen_not_asf", &g_parser[ADJ_MO_1STMODE_SEL][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_MO_1STMODE_SEL},

	/* ADJ_MO_ASF No EdgeThresh:4 */
	{"mo_advanced_spatial_filter.T0T1_div_high", &g_parser[ADJ_MO_ASF][0].argu[27 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.T0T1_div_high_delta", &g_parser[ADJ_MO_ASF][0].argu[28 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.T0T1_div_high_strength", &g_parser[ADJ_MO_ASF][0].argu[29 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.T0T1_div_low", &g_parser[ADJ_MO_ASF][0].argu[23 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.T0T1_div_low_delta", &g_parser[ADJ_MO_ASF][0].argu[24 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.T0T1_div_low_strength", &g_parser[ADJ_MO_ASF][0].argu[25 * 4], MAP_TO_S32, 1, INVALID_CONTAINER_ID},
	{"mo_advanced_spatial_filter.T0T1_div_mid_strength", &g_parser[ADJ_MO_ASF][0].argu[26 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.T0_down", &g_parser[ADJ_MO_ASF][0].argu[14 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.T0_up", &g_parser[ADJ_MO_ASF][0].argu[10 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.T1_down", &g_parser[ADJ_MO_ASF][0].argu[15 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.T1_up", &g_parser[ADJ_MO_ASF][0].argu[11 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.alpha_max_down", &g_parser[ADJ_MO_ASF][0].argu[13 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.alpha_max_up", &g_parser[ADJ_MO_ASF][0].argu[9 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.alpha_min_down", &g_parser[ADJ_MO_ASF][0].argu[12 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.alpha_min_up", &g_parser[ADJ_MO_ASF][0].argu[8 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.directional_decide_t0", &g_parser[ADJ_MO_ASF][0].argu[6 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.directional_decide_t1", &g_parser[ADJ_MO_ASF][0].argu[7 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.enable", &g_parser[ADJ_MO_ASF][0].argu[0], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.fir_specify", &g_parser[ADJ_MO_ASF][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.fir_strength_dir", &g_parser[ADJ_MO_ASF][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.fir_strength_iso", &g_parser[ADJ_MO_ASF][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.fir_wide_edge_detect", &g_parser[ADJ_MO_ASF][0].argu[5 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.level_str_adjust_high", &g_parser[ADJ_MO_ASF][0].argu[20 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.level_str_adjust_high_delta", &g_parser[ADJ_MO_ASF][0].argu[21 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.level_str_adjust_high_strength", &g_parser[ADJ_MO_ASF][0].argu[22 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.level_str_adjust_low", &g_parser[ADJ_MO_ASF][0].argu[16 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.level_str_adjust_low_delta", &g_parser[ADJ_MO_ASF][0].argu[17 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.level_str_adjust_low_strength", &g_parser[ADJ_MO_ASF][0].argu[18 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.level_str_adjust_mid_strength", &g_parser[ADJ_MO_ASF][0].argu[19 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.max_change_down", &g_parser[ADJ_MO_ASF][0].argu[32 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.max_change_not_T0T1_alpha", &g_parser[ADJ_MO_ASF][0].argu[30 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.max_change_up", &g_parser[ADJ_MO_ASF][0].argu[31 * 4], MAP_TO_S32, 1, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.fir_coefs", &g_parser[ADJ_MO_ASF][4].argu[0], MAP_TO_S16, 9 * 25, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.fir_per_dir_fir_dir_amounts", &g_parser[ADJ_MO_ASF][3].argu[0], MAP_TO_U16, 9, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.fir_per_dir_fir_dir_strengths", &g_parser[ADJ_MO_ASF][2].argu[0], MAP_TO_U16, 9, ADJ_MO_ASF},
	{"mo_advanced_spatial_filter.fir_per_dir_fir_iso_strengths", &g_parser[ADJ_MO_ASF][1].argu[0], MAP_TO_U16, 9, ADJ_MO_ASF},

	/* ADJ_MO_1ST_SHARPEN_BOTH */
	{"mo_sharpen_noise_filter_both.edge_thresh", &g_parser[ADJ_MO_1ST_SHARPEN_BOTH][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_BOTH},
	{"mo_sharpen_noise_filter_both.enable", &g_parser[ADJ_MO_1ST_SHARPEN_BOTH][0].argu[0], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_BOTH},
	{"mo_sharpen_noise_filter_both.max_change_down5x5", &g_parser[ADJ_MO_1ST_SHARPEN_BOTH][0].argu[5 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_BOTH},
	{"mo_sharpen_noise_filter_both.max_change_up5x5", &g_parser[ADJ_MO_1ST_SHARPEN_BOTH][0].argu[4 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_BOTH},
	{"mo_sharpen_noise_filter_both.mode", &g_parser[ADJ_MO_1ST_SHARPEN_BOTH][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_BOTH},
	{"mo_sharpen_noise_filter_both.wide_edge_detect", &g_parser[ADJ_MO_1ST_SHARPEN_BOTH][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_BOTH},

	/* ADJ_MO_1ST_SHARPEN_NOISE  No EdgeTresh:5, WideEdgeDetect:6*/
	{"mo_sharpen_noise_filter_noise.T0", &g_parser[ADJ_MO_1ST_SHARPEN_NOISE][0].argu[15 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_NOISE},
	{"mo_sharpen_noise_filter_noise.T1", &g_parser[ADJ_MO_1ST_SHARPEN_NOISE][0].argu[16 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_NOISE},
	{"mo_sharpen_noise_filter_noise.alpha_max", &g_parser[ADJ_MO_1ST_SHARPEN_NOISE][0].argu[18 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_NOISE},
	{"mo_sharpen_noise_filter_noise.alpha_min", &g_parser[ADJ_MO_1ST_SHARPEN_NOISE][0].argu[17 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_NOISE},
	{"mo_sharpen_noise_filter_noise.fir_coefs", &g_parser[ADJ_MO_1ST_SHARPEN_NOISE][4].argu[0 * 4], MAP_TO_S16, 9 * 25, ADJ_MO_1ST_SHARPEN_NOISE},
	{"mo_sharpen_noise_filter_noise.fir_per_dir_fir_dir_amounts", &g_parser[ADJ_MO_1ST_SHARPEN_NOISE][3].argu[0 * 4], MAP_TO_U16, 9, ADJ_MO_1ST_SHARPEN_NOISE},
	{"mo_sharpen_noise_filter_noise.fir_per_dir_fir_dir_strengths", &g_parser[ADJ_MO_1ST_SHARPEN_NOISE][2].argu[0 * 4], MAP_TO_U16, 9, ADJ_MO_1ST_SHARPEN_NOISE},
	{"mo_sharpen_noise_filter_noise.fir_per_dir_fir_iso_strengths", &g_parser[ADJ_MO_1ST_SHARPEN_NOISE][1].argu[0 * 4], MAP_TO_U16, 9, ADJ_MO_1ST_SHARPEN_NOISE},
	{"mo_sharpen_noise_filter_noise.fir_specify", &g_parser[ADJ_MO_1ST_SHARPEN_NOISE][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_NOISE},
	{"mo_sharpen_noise_filter_noise.fir_strength_dir", &g_parser[ADJ_MO_1ST_SHARPEN_NOISE][0].argu[4 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_NOISE},
	{"mo_sharpen_noise_filter_noise.fir_strength_iso", &g_parser[ADJ_MO_1ST_SHARPEN_NOISE][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_NOISE},
	{"mo_sharpen_noise_filter_noise.level_str_adjust_high", &g_parser[ADJ_MO_1ST_SHARPEN_NOISE][0].argu[11 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_NOISE},
	{"mo_sharpen_noise_filter_noise.level_str_adjust_high_delta", &g_parser[ADJ_MO_1ST_SHARPEN_NOISE][0].argu[12 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_NOISE},
	{"mo_sharpen_noise_filter_noise.level_str_adjust_high_strength", &g_parser[ADJ_MO_1ST_SHARPEN_NOISE][0].argu[13 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_NOISE},
	{"mo_sharpen_noise_filter_noise.level_str_adjust_low", &g_parser[ADJ_MO_1ST_SHARPEN_NOISE][0].argu[7 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_NOISE},
	{"mo_sharpen_noise_filter_noise.level_str_adjust_low_delta", &g_parser[ADJ_MO_1ST_SHARPEN_NOISE][0].argu[8 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_NOISE},
	{"mo_sharpen_noise_filter_noise.level_str_adjust_low_strength", &g_parser[ADJ_MO_1ST_SHARPEN_NOISE][0].argu[9 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_NOISE},
	{"mo_sharpen_noise_filter_noise.level_str_adjust_mid_strength", &g_parser[ADJ_MO_1ST_SHARPEN_NOISE][0].argu[10 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_NOISE},
	{"mo_sharpen_noise_filter_noise.level_str_adjust_not_T0T1_level_based", &g_parser[ADJ_MO_1ST_SHARPEN_NOISE][0].argu[14 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_NOISE},
	{"mo_sharpen_noise_filter_noise.max_change_down", &g_parser[ADJ_MO_1ST_SHARPEN_NOISE][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_NOISE},
	{"mo_sharpen_noise_filter_noise.max_change_up", &g_parser[ADJ_MO_1ST_SHARPEN_NOISE][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_NOISE},

	/* ADJ_MO_1ST_SHARPEN_FIR */
	{"mo_sharpen_noise_filter_sharpen.fir_coefs", &g_parser[ADJ_MO_1ST_SHARPEN_FIR][4].argu[0 * 4], MAP_TO_S16, 9 * 25, ADJ_MO_1ST_SHARPEN_FIR},
	{"mo_sharpen_noise_filter_sharpen.fir_per_dir_fir_dir_amounts", &g_parser[ADJ_MO_1ST_SHARPEN_FIR][3].argu[0 * 4], MAP_TO_U16, 9, ADJ_MO_1ST_SHARPEN_FIR},
	{"mo_sharpen_noise_filter_sharpen.fir_per_dir_fir_dir_strengths", &g_parser[ADJ_MO_1ST_SHARPEN_FIR][2].argu[0 * 4], MAP_TO_U16, 9, ADJ_MO_1ST_SHARPEN_FIR},
	{"mo_sharpen_noise_filter_sharpen.fir_per_dir_fir_iso_strengths", &g_parser[ADJ_MO_1ST_SHARPEN_FIR][1].argu[0 * 4], MAP_TO_U16, 9, ADJ_MO_1ST_SHARPEN_FIR},
	{"mo_sharpen_noise_filter_sharpen.fir_specify", &g_parser[ADJ_MO_1ST_SHARPEN_FIR][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_FIR},
	{"mo_sharpen_noise_filter_sharpen.fir_strength_dir", &g_parser[ADJ_MO_1ST_SHARPEN_FIR][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_FIR},
	{"mo_sharpen_noise_filter_sharpen.fir_strength_iso", &g_parser[ADJ_MO_1ST_SHARPEN_FIR][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_FIR},

	/* ADJ_MO_1ST_SHARPEN_CORING */
	{"mo_sharpen_noise_filter_sharpen_coring.coring_table", &g_parser[ADJ_MO_1ST_SHARPEN_CORING][1].argu[0], MAP_TO_U8, TONE_CURVE_SIZE, ADJ_MO_1ST_SHARPEN_CORING},
	{"mo_sharpen_noise_filter_sharpen_coring.fractional_bits", NULL, MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_CORING},

	/* ADJ_MO_1ST_SHARPEN_CORING_INDEX_SCALE */
	{"mo_sharpen_noise_filter_sharpen_coring_index_scale.high", &g_parser[ADJ_MO_1ST_SHARPEN_CORING_INDEX_SCALE][0].argu[4 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_CORING_INDEX_SCALE},
	{"mo_sharpen_noise_filter_sharpen_coring_index_scale.high_delta", &g_parser[ADJ_MO_1ST_SHARPEN_CORING_INDEX_SCALE][0].argu[5 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_CORING_INDEX_SCALE},
	{"mo_sharpen_noise_filter_sharpen_coring_index_scale.high_strength", &g_parser[ADJ_MO_1ST_SHARPEN_CORING_INDEX_SCALE][0].argu[6 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_CORING_INDEX_SCALE},
	{"mo_sharpen_noise_filter_sharpen_coring_index_scale.low", &g_parser[ADJ_MO_1ST_SHARPEN_CORING_INDEX_SCALE][0].argu[0], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_CORING_INDEX_SCALE},
	{"mo_sharpen_noise_filter_sharpen_coring_index_scale.low_delta", &g_parser[ADJ_MO_1ST_SHARPEN_CORING_INDEX_SCALE][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_CORING_INDEX_SCALE},
	{"mo_sharpen_noise_filter_sharpen_coring_index_scale.low_strength", &g_parser[ADJ_MO_1ST_SHARPEN_CORING_INDEX_SCALE][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_CORING_INDEX_SCALE},
	{"mo_sharpen_noise_filter_sharpen_coring_index_scale.mid_strength", &g_parser[ADJ_MO_1ST_SHARPEN_CORING_INDEX_SCALE][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_CORING_INDEX_SCALE},

	/* ADJ_MO_1ST_SHARPEN_CORING_MIN_RESULT */
	{"mo_sharpen_noise_filter_sharpen_min_coring_result.high", &g_parser[ADJ_MO_1ST_SHARPEN_CORING_MIN_RESULT][0].argu[4 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_CORING_MIN_RESULT},
	{"mo_sharpen_noise_filter_sharpen_min_coring_result.high_delta", &g_parser[ADJ_MO_1ST_SHARPEN_CORING_MIN_RESULT][0].argu[5 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_CORING_MIN_RESULT},
	{"mo_sharpen_noise_filter_sharpen_min_coring_result.high_strength", &g_parser[ADJ_MO_1ST_SHARPEN_CORING_MIN_RESULT][0].argu[6 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_CORING_MIN_RESULT},
	{"mo_sharpen_noise_filter_sharpen_min_coring_result.low", &g_parser[ADJ_MO_1ST_SHARPEN_CORING_MIN_RESULT][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_CORING_MIN_RESULT},
	{"mo_sharpen_noise_filter_sharpen_min_coring_result.low_delta", &g_parser[ADJ_MO_1ST_SHARPEN_CORING_MIN_RESULT][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_CORING_MIN_RESULT},
	{"mo_sharpen_noise_filter_sharpen_min_coring_result.low_strength", &g_parser[ADJ_MO_1ST_SHARPEN_CORING_MIN_RESULT][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_CORING_MIN_RESULT},
	{"mo_sharpen_noise_filter_sharpen_min_coring_result.mid_strength", &g_parser[ADJ_MO_1ST_SHARPEN_CORING_MIN_RESULT][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_CORING_MIN_RESULT},

	/* ADJ_MO_1ST_SHARPEN_CORING_SCALE_CORING */
	{"mo_sharpen_noise_filter_sharpen_scale_coring.high", &g_parser[ADJ_MO_1ST_SHARPEN_CORING_SCALE_CORING][0].argu[4 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_CORING_SCALE_CORING},
	{"mo_sharpen_noise_filter_sharpen_scale_coring.high_delta", &g_parser[ADJ_MO_1ST_SHARPEN_CORING_SCALE_CORING][0].argu[5 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_CORING_SCALE_CORING},
	{"mo_sharpen_noise_filter_sharpen_scale_coring.high_strength", &g_parser[ADJ_MO_1ST_SHARPEN_CORING_SCALE_CORING][0].argu[6 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_CORING_SCALE_CORING},
	{"mo_sharpen_noise_filter_sharpen_scale_coring.low", &g_parser[ADJ_MO_1ST_SHARPEN_CORING_SCALE_CORING][0].argu[0 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_CORING_SCALE_CORING},
	{"mo_sharpen_noise_filter_sharpen_scale_coring.low_delta", &g_parser[ADJ_MO_1ST_SHARPEN_CORING_SCALE_CORING][0].argu[1 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_CORING_SCALE_CORING},
	{"mo_sharpen_noise_filter_sharpen_scale_coring.low_strength", &g_parser[ADJ_MO_1ST_SHARPEN_CORING_SCALE_CORING][0].argu[2 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_CORING_SCALE_CORING},
	{"mo_sharpen_noise_filter_sharpen_scale_coring.mid_strength", &g_parser[ADJ_MO_1ST_SHARPEN_CORING_SCALE_CORING][0].argu[3 * 4], MAP_TO_S32, 1, ADJ_MO_1ST_SHARPEN_CORING_SCALE_CORING},


	/* Not ready */
	{"aaa_function.adj_op", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"aaa_function.ae_op", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"aaa_function.af_op", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"aaa_function.awb_op", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"ae_info.agc_index", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"ae_info.dgain", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"ae_info.iris_index", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"ae_info.shutter_index", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},


	{"chromatic_aberration_correction.enable", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"deferred_black_level.enable", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"dgain_saturation_level.level_blue", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"dgain_saturation_level.level_green_even", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"dgain_saturation_level.level_green_odd", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"dgain_saturation_level.level_red", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"dzoom.enable", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"global_dgain.gain", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},




	{"li_cfa_leakage_filter.alpha_bb", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"li_cfa_leakage_filter.alpha_br", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"li_cfa_leakage_filter.alpha_rb", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"li_cfa_leakage_filter.alpha_rr", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"li_cfa_leakage_filter.enable", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"li_cfa_leakage_filter.saturation_level", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},

	{"mo_cfa_leakage_filter.alpha_bb", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"mo_cfa_leakage_filter.alpha_br", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"mo_cfa_leakage_filter.alpha_rb", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"mo_cfa_leakage_filter.alpha_rr", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"mo_cfa_leakage_filter.enable", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"mo_cfa_leakage_filter.saturation_level", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},

	{"static_bad_pixel_correction.enable", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},

	{"#system.frame_number", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"system.main_height", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"system.main_width", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"#system.number_of_frames", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"#system.preview_height", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"#system.preview_width", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"system.raw_bayer", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"system.raw_height", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"system.raw_pitch", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"system.raw_resolution", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"system.raw_width", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},




	{"vignette_compensation.enable", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"vignette_compensation.gain_shift", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"warp_compensation.enable", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"wb_gains.b_gain", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"wb_gains.g_gain", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"wb_gains.r_gain", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"system.tuning_mode", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"system.raw_path", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"color_correction.reg_path", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
	{"color_correction.three_d_path", NULL, MAP_TO_U8, 0, INVALID_CONTAINER_ID},
};

static int parse_name_to_map_index(Mapping * Map, char * s)
{
	int i = 0;

	while (NULL != Map[i].TokenName) {
		if (0 == strcmp(Map[i].TokenName, s))
			return i;
		else
			++i;
	}

	return -1;
}

int verify_args(Mapping *reg)
{
	int i, size = 0;
	u8 *data_u8 = NULL;
	int type_size[MAP_DATA_TYPE_NUM] = {sizeof(u32), sizeof(u16), sizeof(u8),
			sizeof(s32), sizeof(s16), sizeof(s8), sizeof(float), 64};

	printf("\nMAP: name:%s, Type: %d, addr:0x%x, value_num:%d \n",
		reg->TokenName, reg->Type, (u32)reg->Address, reg->Value_num);

	size = reg->Value_num * type_size[reg->Type];
	if ((data_u8 = (u8 *)malloc(size)) == NULL) {
		return -1;
	}

	memcpy(data_u8, reg->Address, size);

	for (i = 0; i < reg->Value_num; i++) {
		if (i % 8 == 0) {
			printf("\n");
		}

		switch (reg->Type) {
		case MAP_TO_U32:
			printf("[%4d] = 0x%04x   \t", i, *((u32 *)data_u8 + i));
			break;
		case MAP_TO_U16:
			printf("[%4d] = 0x%04x   \t", i, *((u16 *)data_u8 + i));
			break;
		case MAP_TO_U8:
			printf("[%4d] = 0x%04x   \t", i, *((u8 *)data_u8 + i));
			break;
		case MAP_TO_S32:
			printf("[%4d] = 0x%04x   \t", i, *((s32 *)data_u8 + i));
			break;
		case MAP_TO_S16:
			printf("[%4d] = 0x%04x   \t", i, *((s16 *)data_u8 + i));
			break;
		case MAP_TO_S8:
			printf("[%4d] = 0x%04x   \t", i, *((s8 *)data_u8 + i));
			break;
		case MAP_TO_DOUBLE:
			break;
		case MAP_TO_STRING:
			break;
		default:
			break;
		}
	}
	printf("\n");

	free(data_u8);
	data_u8 = NULL;

	return 0;
}

static int copy_data(Mapping *reg, int *value)
{
	int i, size = reg->Value_num;

	for (i = 0; i < size; i ++) {
		switch (reg->Type) {
		case MAP_TO_U32:
			*((u32 *)(reg->Address) + i) = value[i];
			break;
		case MAP_TO_U16:
			*((u16 *)(reg->Address) + i) = value[i];
			break;
		case MAP_TO_U8:
			*((u8 *)(reg->Address) + i) = value[i];
			break;
		case MAP_TO_S32:
			*((s32 *)(reg->Address) + i) = value[i];
		break;
		case MAP_TO_S16:
			*((s16 *)(reg->Address) + i) = value[i];
			break;

		case MAP_TO_S8:
			*((s8 *)(reg->Address) + i) = value[i];
			break;

		case MAP_TO_DOUBLE:
			break;

		case MAP_TO_STRING:
			break;

		default:
			return -1;
		}
	}
	return 0;
}

static int check_map(Mapping *Regs, int value_num)
{
	int ret = 0;

	if (Regs->container_id == INVALID_CONTAINER_ID) {
//		printf("Not valid container id\n");
		ret = 1;
	} else if (Regs->Address == NULL) {
//		printf("The Address is NULL\n");
		ret = 1;
	} else if (Regs->Value_num != value_num) {
//		printf("The value num are not matched\n");
		ret = 1;
	}

	return ret;
}

static int get_multi_arg(char *input_str, char *param, int *argarr, int *argcnt)
{
	int i = 0;
	char *delim = " ,:\n\t";
	char *ptr;
	*argcnt = 0;

	ptr = strtok(input_str, delim);
	if (ptr == NULL)
		return 0;
	strcpy(param, ptr);

	while (1) {
		ptr = strtok(NULL, delim);
		if (ptr == NULL)
			break;
		argarr[i++] = atoi(ptr);
	}

	*argcnt = i;
	return 0;
}

static int parse_adj_txt_file(char *filename)
{
	char line[1024];
	char param_name[256];
	int value[MAX_ARGU_U32];
	int value_num = 0;
	int i;
	FILE *fp;

	memset(g_parser, 0, MAX_STRUCT_MEMBER * ADJ_FILTER_NUM * sizeof(parser_t));
	if ((fp = fopen(filename, "r")) == NULL) {
		PARSE_ERROR("Open file:%s error\n", filename);
		return -1;
	}

	while (fgets(line, sizeof(line), fp) != NULL) {
		get_multi_arg(line, param_name, value, &value_num);
//		printf("line : name:%s, value_num:%d \n", param_name, value_num);

		if (value_num == 0) {
			continue;
		}
		if ((i = parse_name_to_map_index(ImgRegs, param_name)) >= 0) {
			if (check_map(&ImgRegs[i], value_num)) {
				continue;
			}
			copy_data(&ImgRegs[i], value);
//			verify_args(&ImgRegs[i]);
		}
	}

	if (fp >= 0) {
		fclose(fp);
	}

	return 0;

}

