/*
 *
 * idsp_test
 *
 * History:
 *	2015/09/10 - [Jingyang Qiu] Created this file
 *
 * Description :
 *	Load the tuned file which generated by Img tuning tool.
 *
 * Copyright (C) 2015 Ambarella, Inc.
 *
 * This file and its contents ("Software") are protected by intellectual
 * property rights including, without limitation, U.S. and/or foreign
 * copyrights. This Software is also the confidential and proprietary
 * information of Ambarella, Inc. and its licensors. You may not use, reproduce,
 * disclose, distribute, modify, or otherwise prepare derivative works of this
 * Software or any portion thereof except pursuant to a signed license agreement
 * or nondisclosure agreement with Ambarella, Inc. or its authorized affiliates.
 * In the absence of such an agreement, you agree to promptly notify and return
 * this Software to Ambarella, Inc.
 *
 * THIS SOFTWARE IS PROVIDED "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF NON-INFRINGEMENT,
 * MERCHANTABILITY, AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
 * IN NO EVENT SHALL AMBARELLA, INC. OR ITS AFFILIATES BE LIABLE FOR ANY DIRECT,
 * INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
 * (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; COMPUTER FAILURE OR MALFUNCTION; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 */

//dict for vin

//[0] is main key, followed by sub keys
char* pipeline_dict[] = 	{"pipeline", 	"enc_mode", "raw2enc", "raw_cap", "raw_max_width", "raw_max_height", "exposure_num", "duration", "next_cfg_file"};
char* vin_dict[] = 		{"vin", 	"sensor_id", "video_mode", "hdr_mode", "width", "height", "fps", "bit_resolution", "mirror", "bayer_pattern", "sensor_name"};
char* vout0_dict[] = 		{"vout0", 	"enable", "input", "mode", "width", "height", "device", "lcd_model_index"};
char* vout1_dict[] = 		{"vout1", 	"enable", "input", "mode", "width", "height", "device", "lcd_model_index"};
char* osd_dict[] =		{"osd", 	"from_mixer_a", "from_mixer_b"};
//char* dummy_win_dict[] = 	{"dummy_win", 	"width", "height"};
//char* active_win_dict[] = 		{"active_win", 	"width", "height"};
char* main_buf_dict[] = 	{"main_buf", 	"input_width", "input_height", "input_offset_x", "input_offset_y", "max_width", "max_height", "width", "height", "type"};
char* second_buf_dict[] = 	{"second_buf", 	"input_width", "input_height", "input_offset_x", "input_offset_y", "max_width", "max_height", "width", "height", "type"};
char* third_buf_dict[] = 	{"third_buf", 	"input_width", "input_height", "input_offset_x", "input_offset_y", "max_width", "max_height", "width", "height", "type"};
char* fourth_buf_dict[] = 	{"fourth_buf", 	"input_width", "input_height", "input_offset_x", "input_offset_y", "max_width", "max_height", "width", "height", "type"};

char* stream_a_dict[] = 	{"stream_a", 	"width", "height", "max_width", "max_height", "m", "n", "bit_rate", "quality", "h_flip", "v_flip", "rotate", "fps_ratio", "source", "type"};
char* stream_b_dict[] = 	{"stream_b", 	"width", "height", "max_width", "max_height", "m", "n", "bit_rate", "quality", "h_flip", "v_flip", "rotate", "fps_ratio", "source", "type"};
char* stream_c_dict[] = 	{"stream_c", 	"width", "height", "max_width", "max_height", "m", "n", "bit_rate", "quality", "h_flip", "v_flip", "rotate", "fps_ratio", "source", "type"};
char* stream_d_dict[] = 	{"stream_d", 	"width", "height", "max_width", "max_height", "m", "n", "bit_rate", "quality", "h_flip", "v_flip", "rotate", "fps_ratio", "source", "type"};
