#!/bin/sh
#
# Init system config
#

start()
{
	for sysconf in $(find /etc/sysctl.d -type f -name "*.conf"); do
		/sbin/sysctl -p ${sysconf}
	done
}

stop(){}

restart() {
	stop
	start
}

case "$1" in
  start)
	start
	;;
  stop)
	stop
	;;
  restart|reload)
	restart
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

