##
## prebuild/imgproc/img_data/arch_s2l/make.inc
##
## History:
##    2012/11/06 - [Zhaoyang Chen] Created file
##    2014/03/27 - [Jingyang Qiu] modified file
##
## Copyright (C) 2012-2016, Ambarella, Inc.
##
## All rights reserved. No Part of this file may be reproduced, stored
## in a retrieval system, or transmitted, in any form, or by any means,
## electronic, mechanical, photocopying, recording, or otherwise,
## without the prior consent of Ambarella, Inc.
##

include $(call all-subdir-makefiles)

