#
# arch/arm/mach-ambarella/soc/Makefile
#
# Author: Cao Rongrong <rrcao@ambarella.com>
#
# Copyright (C) 2012-2016, Ambarella, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#

obj-$(CONFIG_PLAT_AMBARELLA_A5S)			+= a5s.o
obj-$(CONFIG_PLAT_AMBARELLA_A7L)			+= a7l.o
obj-$(CONFIG_PLAT_AMBARELLA_S2_CORTEX)			+= s2-cortex.o
obj-$(CONFIG_PLAT_AMBARELLA_S2E)			+= s2e.o
obj-$(CONFIG_PLAT_AMBARELLA_S2L)			+= s2l.o
obj-$(CONFIG_PLAT_AMBARELLA_S3)				+= s3.o
obj-$(CONFIG_PLAT_AMBARELLA_S3L)			+= s3l.o

