##
## system/src/flashdb/spinor/make.inc
##
## History:
##    2013/10/24 - [Johnson Diao] created file
##
## Copyright (C) 2013-2017, Ambarella, Inc.
##
## All rights reserved. No Part of this file may be reproduced, stored
## in a retrieval system, or transmitted, in any form, or by any means,
## electronic, mechanical, photocopying, recording, or otherwise,
## without the prior consent of Ambarella, Inc.
##

SPINORDB_SRCS = \
	$(TOP)/src/flashdb/spinor/spinor_flash.c
SPINORDB_OBJS = \
	spinor_flash.o

