#
# arch/arm/plat-ambarella/misc/Makefile
#
# Author: Anthony Ginger <hfjiang@ambarella.com>
#
# Copyright (C) 2004-2011, Ambarella, Inc.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA 02111-1307 USA
#

obj-y						+= hwlock.o
obj-y						+= audio.o
obj-$(CONFIG_PLAT_AMBARELLA_SUPPORT_GDMA)	+= gdma.o
obj-y						+= ambasyncproc.o
obj-y						+= ambcache.o
obj-$(CONFIG_AMBARELLA_SUPPORT_AMBENCH)		+= ambench.o
obj-y						+= ambevent.o
obj-y						+= ambfb.o
obj-y						+= ambsyncproc.o
obj-y						+= event.o
obj-y						+= iav_helper.o
obj-$(CONFIG_AMBARELLA_TIMER_HIGHRES)		+= highres_timer.o
obj-y						+= pmu.o

