##
## Kbuild
##
## History:
##    2015/10/26 - [Jorney] Create
##
## Copyright (C) 2012-2016, Ambarella, Inc.
##
## All rights reserved. No Part of this file may be reproduced, stored
## in a retrieval system, or transmitted, in any form, or by any means,
## electronic, mechanical, photocopying, recording, or otherwise,
## without the prior consent of Ambarella, Inc.
##

EXTRA_CFLAGS		+= $(AMBARELLA_DRV_CFLAGS)
EXTRA_AFLAGS		+= $(AMBARELLA_DRV_AFLAGS)
EXTRA_LDFLAGS		+= $(AMBARELLA_DRV_LDFLAGS)

obj-m += uvc.o
uvc-y := f_uvc.o uvc_stream.o
obj-m += webcam.o

obj-m +=uac.o
uac-y += f_uac1.o uac_stream.o
obj-m += audio.o

