deps_config := \
	unit_test/linux/benchmark/AmbaConfig \
	unit_test/AmbaConfig \
	prebuild/third-party/noarch/realtek-wifi/AmbaConfig \
	prebuild/third-party/noarch/broadcom-wifi/AmbaConfig \
	prebuild/third-party/noarch/atheros-wifi-calib/AmbaConfig \
	prebuild/third-party/noarch/atheros-wifi/AmbaConfig \
	prebuild/third-party/AmbaConfig \
	rootfs/AmbaConfig \
	prebuild/AmbaConfig \
	packages/img_mw/mw/AmbaConfig \
	packages/img_mw/dev/AmbaConfig \
	packages/AmbaConfig \
	oryx/playback_new/AmbaConfig \
	oryx/watchdog/AmbaConfig \
	oryx/video_new/AmbaConfig \
	oryx/video/unit_test/AmbaConfig \
	oryx/video/AmbaConfig \
	oryx/utility/unit_test/AmbaConfig \
	oryx/utility/util/AmbaConfig \
	oryx/utility/osal/AmbaConfig \
	oryx/utility/jpeg_snapshot/AmbaConfig \
	oryx/utility/jpeg_encoder/AmbaConfig \
	oryx/utility/AmbaConfig \
	oryx/upgrade/unit_test/AmbaConfig \
	oryx/upgrade/AmbaConfig \
	oryx/stream/AmbaConfig \
	oryx/cgi/AmbaConfig \
	oryx/services/video_service/AmbaConfig \
	oryx/services/system_service/AmbaConfig \
	oryx/services/sip_service/AmbaConfig \
	oryx/services/service_manager/AmbaConfig \
	oryx/services/service_frame/AmbaConfig \
	oryx/services/rtsp_service/AmbaConfig \
	oryx/services/network_service/AmbaConfig \
	oryx/services/media_service/AmbaConfig \
	oryx/services/image_service/AmbaConfig \
	oryx/services/event_service/AmbaConfig \
	oryx/services/audio_service/AmbaConfig \
	oryx/services/apps_launcher/AmbaConfig \
	oryx/services/api_proxy/AmbaConfig \
	oryx/services/AmbaConfig \
	oryx/protocol/AmbaConfig \
	oryx/network/AmbaConfig \
	oryx/led/unit_test/AmbaConfig \
	oryx/led/AmbaConfig \
	oryx/ipc/unit_test/AmbaConfig \
	oryx/ipc/AmbaConfig \
	oryx/image_quality/unit_test/AmbaConfig \
	oryx/image_quality/AmbaConfig \
	oryx/event/plugins/AmbaConfig \
	oryx/event/AmbaConfig \
	oryx/discovery/AmbaConfig \
	oryx/configure/unit_test/AmbaConfig \
	oryx/configure/AmbaConfig \
	oryx/cloud_storage/AmbaConfig \
	oryx/audio/AmbaConfig \
	oryx/analytics/unit_test/AmbaConfig \
	oryx/analytics/qrcode/AmbaConfig \
	oryx/analytics/AmbaConfig \
	oryx/app/cooee/AmbaConfig \
	oryx/app/wifi_setup/AmbaConfig \
	oryx/app/AmbaConfig \
	oryx/vendors/baiducam/AmbaConfig \
	oryx/vendors/AmbaConfig \
	oryx/AmbaConfig \
	kernel/private/lib/AmbaConfig \
	kernel/private/drivers/cryptochip/AmbaConfig \
	kernel/private/drivers/crypto/AmbaConfig \
	kernel/private/drivers/dsplog/AmbaConfig \
	kernel/private/drivers/debug/AmbaConfig \
	kernel/private/drivers/eis/AmbaConfig \
	kernel/private/drivers/gyro/AmbaConfig \
	kernel/private/drivers/fdet/AmbaConfig \
	kernel/private/drivers/imgproc/AmbaConfig \
	kernel/private/drivers/iav/AmbaConfig \
	kernel/private/drivers/dsp/AmbaConfig \
	kernel/private/drivers/hw_timer/AmbaConfig \
	kernel/private/drivers/msg/AmbaConfig \
	kernel/private/drivers/vout/it66121/AmbaConfig \
	kernel/private/drivers/vout/hdmi/AmbaConfig \
	kernel/private/drivers/vout/digital/AmbaConfig \
	kernel/private/drivers/vout/dve/AmbaConfig \
	kernel/private/drivers/vout/AmbaConfig \
	kernel/private/drivers/lens/evetar_mz128bp2810icr/AmbaConfig \
	kernel/private/drivers/lens/tamron_m13vp288ir/AmbaConfig \
	kernel/private/drivers/lens/AmbaConfig \
	kernel/private/drivers/vin/decoders/AmbaConfig \
	kernel/private/drivers/vin/sensors/sony_imx322/AmbaConfig \
	kernel/private/drivers/vin/sensors/sony_imx178/AmbaConfig \
	kernel/private/drivers/vin/sensors/AmbaConfig \
	kernel/private/drivers/vin/AmbaConfig \
	kernel/private/drivers/AmbaConfig \
	kernel/external/atmel/AmbaConfig \
	kernel/external/multivinfpga/AmbaConfig \
	kernel/external/compat/AmbaConfig \
	kernel/external/realtek/AmbaConfig \
	kernel/external/broadcom/AmbaConfig \
	kernel/external/atheros/AmbaConfig \
	kernel/external/marvell/AmbaConfig \
	kernel/AmbaConfig \
	app/utility/upgrade_partition/AmbaConfig \
	app/utility/mptool/AmbaConfig \
	app/utility/jpg_enc/AmbaConfig \
	app/utility/dsp_tool/AmbaConfig \
	app/utility/dng_tool/AmbaConfig \
	app/utility/amb_scripts/AmbaConfig \
	app/utility/af_value_server/AmbaConfig \
	app/ipcam/fastboot_app/darwin_injector/AmbaConfig \
	app/ipcam/fastboot_app/elektra_boot/AmbaConfig \
	app/ipcam/fastboot_app/AmbaConfig \
	app/ipcam/fastboot_smart3a/AmbaConfig \
	app/ipcam/fastboot_audio/AmbaConfig \
	app/ipcam/http_uploader/AmbaConfig \
	app/ipcam/smart_ldc/AmbaConfig \
	app/ipcam/autorun_services/AmbaConfig \
	app/ipcam/rtsp/AmbaConfig \
	app/AmbaConfig \
	amboot/config/amboot.amboot.in \
	amboot/config/amboot.hw.in \
	amboot/config/amboot.mem.in \
	boards/AmbaConfig \
	amboot/AmbaConfig \
	/home/jchen/Projects/kasa/ambarella/AmbaConfig

.config config.h: \
	$(deps_config)


$(deps_config): ;
