##
## Kbuild
##
## History:
##    2014/07/29 - [Lei Hong] Create
##
## Copyright (C) 2004-2018, Ambarella, Inc.
##
## All rights reserved. No Part of this file may be reproduced, stored
## in a retrieval system, or transmitted, in any form, or by any means,
## electronic, mechanical, photocopying, recording, or otherwise,
## without the prior consent of Ambarella, Inc.
##

EXTRA_CFLAGS		+= $(AMBARELLA_DRV_CFLAGS)
EXTRA_AFLAGS		+= $(AMBARELLA_DRV_AFLAGS)
EXTRA_LDFLAGS		+= $(AMBARELLA_DRV_LDFLAGS)

obj-m := msg.o
msg-y := msg_print.o msg_drv.o


