/*
 * iav_enc_limit.c
 *
 * History:
 *	2013/02/25 - [Cao Rongrong] created file
 *
 * Copyright (C) 2012-2016, Ambarella, Inc.
 *
 * All rights reserved. No Part of this file may be reproduced, stored
 * in a retrieval system, or transmitted, in any form, or by any means,
 * electronic, mechanical, photocopying, recording, or otherwise,
 * without the prior consent of Ambarella, Inc.
 *
 */
#include <asm/uaccess.h>
#include "iav.h"


struct iav_buffer_limitation G_buffer_limit[IAV_SRCBUF_NUM] =
{
	[IAV_SRCBUF_MN] = {
		.max_win = {MNBUF_LIMIT_MAX_WIDTH, MNBUF_LIMIT_MAX_HEIGHT},
		.max_zoomin_factor = MNBUF_MAX_ZOOMIN_FACTOR,
		.max_zoomout_factor = MNBUF_MAX_ZOOMOUT_FACTOR,
	},

	[IAV_SRCBUF_PC] = {
		.max_win = {PCBUF_LIMIT_MAX_WIDTH, PCBUF_LIMIT_MAX_HEIGHT},
		.max_zoomin_factor = PCBUF_MAX_ZOOMIN_FACTOR,
		.max_zoomout_factor = PCBUF_MAX_ZOOMOUT_FACTOR,
	},

	[IAV_SRCBUF_PB] = {
		.max_win = {PBBUF_LIMIT_MAX_WIDTH, PBBUF_LIMIT_MAX_HEIGHT},
		.max_zoomin_factor = PBBUF_MAX_ZOOMIN_FACTOR,
		.max_zoomout_factor = PBBUF_MAX_ZOOMOUT_FACTOR,
	},

	[IAV_SRCBUF_PA] = {
		.max_win = {PABUF_LIMIT_MAX_WIDTH, PABUF_LIMIT_MAX_HEIGHT},
		.max_zoomin_factor = PABUF_MAX_ZOOMIN_FACTOR,
		.max_zoomout_factor = PABUF_MAX_ZOOMOUT_FACTOR,
	},

	[IAV_SRCBUF_PMN] = {
		.max_win = {MNBUF_LIMIT_MAX_WIDTH, MNBUF_LIMIT_MAX_HEIGHT},
		.max_zoomin_factor = MNBUF_MAX_ZOOMIN_FACTOR,
		.max_zoomout_factor = MNBUF_MAX_ZOOMOUT_FACTOR,
	},

	[IAV_SRCBUF_EFM] = {
		.max_win = {MNBUF_LIMIT_MAX_WIDTH, MNBUF_LIMIT_MAX_HEIGHT},
		.max_zoomin_factor = 1,
		.max_zoomout_factor = 1,
	},
};

struct iav_system_load G_system_load[IAV_CHIP_ID_S2L_NUM] =
{
	[IAV_CHIP_ID_S2L_22M - IAV_CHIP_ID_S2LM_FIRST] = {
		.system_load = SYS_ENC_LOAD_S2L_22M,
		.desc = "720p60",
		.max_enc_num = IAV_STREAM_MAX_NUM_ALL,
	},
	[IAV_CHIP_ID_S2L_33M - IAV_CHIP_ID_S2LM_FIRST] = {
		.system_load = SYS_ENC_LOAD_S2L_33M,
		.desc = "1080p31 + 480p30 + CIFp30",
		.max_enc_num = IAV_STREAM_MAX_NUM_ALL,
	},
	[IAV_CHIP_ID_S2L_55M - IAV_CHIP_ID_S2LM_FIRST] = {
		.system_load = SYS_ENC_LOAD_S2L_55M,
		.desc = "3Mp30 + 480p30",
		.max_enc_num = IAV_STREAM_MAX_NUM_ALL,
	},
	[IAV_CHIP_ID_S2L_99M - IAV_CHIP_ID_S2LM_FIRST] = {
		.system_load = SYS_ENC_LOAD_S2L_99M,
		.desc = "5Mp20 + 480p20",
		.max_enc_num = IAV_STREAM_MAX_NUM_ALL,
	},
	[IAV_CHIP_ID_S2L_63 - IAV_CHIP_ID_S2LM_FIRST] = {
		.system_load = SYS_ENC_LOAD_S2L_63,
		.desc = "3Mp30 + 480p30",
		.max_enc_num = IAV_STREAM_MAX_NUM_ALL,
	},
	[IAV_CHIP_ID_S2L_66 - IAV_CHIP_ID_S2LM_FIRST] = {
		.system_load = SYS_ENC_LOAD_S2L_66,
		.desc = "5Mp30 + 480p30",
		.max_enc_num = IAV_STREAM_MAX_NUM_ALL,
	},
	[IAV_CHIP_ID_S2L_88 - IAV_CHIP_ID_S2LM_FIRST] = {
		.system_load = SYS_ENC_LOAD_S2L_88,
		.desc = "5Mp30 + 480p30",
		.max_enc_num = IAV_STREAM_MAX_NUM_ALL,
	},
	[IAV_CHIP_ID_S2L_99 - IAV_CHIP_ID_S2LM_FIRST] = {
		.system_load = SYS_ENC_LOAD_S2L_99,
		.desc = "1080p110",
		.max_enc_num = IAV_STREAM_MAX_NUM_ALL,
	},
	[IAV_CHIP_ID_S2L_TEST - IAV_CHIP_ID_S2LM_FIRST] = {
		.system_load = SYS_ENC_LOAD_S2L_TEST,
		.desc = "5Mp20 + 480p20",
		.max_enc_num = IAV_STREAM_MAX_NUM_ALL,
	},
};

struct iav_enc_limitation G_encode_limit[DSP_ENCODE_MODE_TOTAL_NUM] =
{
	[DSP_NORMAL_ISO_MODE] = {
		.max_main = {MAX_WIDTH_IN_HIGH_MP, MAX_HEIGHT_IN_HIGH_MP},
		.min_main = {MIN_WIDTH_IN_HIGH_MP, MIN_HEIGHT_IN_HIGH_MP},
		.min_enc = {MIN_WIDTH_IN_STREAM_ROTATE, MIN_HEIGHT_IN_STREAM},
		.max_enc_num = IAV_MAX_ENCODE_STREAMS_NUM,
		.max_chroma_radius = CHROMA_RADIUS_32,
		.max_wide_chroma_radius = 0,
		.max_enc_MB = LOAD_1080P110,
		//.max_pps = MAX_CAP_PPS_IN_FULL_FPS,
		.rotate_supported = 1,
		.rawcap_supported = 1,
		.vout_swap_supported = 1,
		.lens_warp_supported = 0,
		.iso_supported = ISO_TYPE_LOW,
		.high_mp_vin_supported = 1,
		.linear_supported = 1,
		.hdr_2x_supported = HDR_TYPE_BASIC,
		.hdr_3x_supported = HDR_TYPE_OFF,
		.mixer_b_supported = 1,
		.pm_bpc_supported = 1,
		.pm_mctf_supported = 1,
		.wcr_supported = 0,
		.idsp_upsample_supported = 1,
		.me0_supported = ME0_SCALE_OFF,
		.enc_raw_rgb_supported = 0,
		.enc_raw_yuv_supported = 1,
		.enc_from_mem_supported = 1,
	},

	[DSP_MULTI_REGION_WARP_MODE] = {
		.max_main = {MAX_WIDTH_IN_WARP, MAX_HEIGHT_IN_WARP},
		.min_main = {MIN_WIDTH_IN_WARP, MIN_HEIGHT_IN_WARP},
		.min_enc = {MIN_WIDTH_IN_STREAM, MIN_HEIGHT_IN_STREAM},
		.max_enc_num = IAV_MAX_ENCODE_STREAMS_NUM,
		.max_chroma_radius = CHROMA_RADIUS_128,
		.max_wide_chroma_radius = 0,
		.max_enc_MB = LOAD_4MP30,
		//.max_pps = MAX_CAP_PPS_IN_FULL_FPS,
		.rotate_supported = 0,
		.rawcap_supported = 0,
		.vout_swap_supported = 1,
		.lens_warp_supported = 1,
		.iso_supported = ISO_TYPE_ADVANCED,
		.high_mp_vin_supported = 1,
		.linear_supported = 1,
		.hdr_2x_supported = HDR_TYPE_BASIC,
		.hdr_3x_supported = HDR_TYPE_OFF,
		.mixer_b_supported = 1,
		.pm_bpc_supported = 1,
		.pm_mctf_supported = 0,
		.wcr_supported = 0,
		.idsp_upsample_supported = 1,
		.me0_supported = ME0_SCALE_OFF,
		.enc_raw_rgb_supported = 0,
		.enc_raw_yuv_supported = 0,
		.enc_from_mem_supported = 0,
	},

	[DSP_BLEND_ISO_MODE] = {
		.max_main = {MAX_WIDTH_IN_HIGH_MP, MAX_HEIGHT_IN_HIGH_MP},
		.min_main = {MIN_WIDTH_IN_HIGH_MP, MIN_HEIGHT_IN_HIGH_MP},
		.min_enc = {MIN_WIDTH_IN_STREAM_ROTATE, MIN_HEIGHT_IN_STREAM},
		.max_enc_num = IAV_MAX_ENCODE_STREAMS_NUM,
		.max_chroma_radius = CHROMA_RADIUS_128,
		.max_wide_chroma_radius = CHROMA_RADIUS_128,
		.max_enc_MB = LOAD_5MP30,
		//.max_pps = MAX_CAP_PPS_IN_FULL_FPS,
		.rotate_supported = 1,
		.rawcap_supported = 1,
		.vout_swap_supported = 1,
		.lens_warp_supported = 0,
		.iso_supported = ISO_TYPE_BLEND,
		.high_mp_vin_supported = 1,
		.linear_supported = 1,
		.hdr_2x_supported = HDR_TYPE_BASIC,
		.hdr_3x_supported = HDR_TYPE_OFF,
		.mixer_b_supported = 0,
		.pm_bpc_supported = 1,
		.pm_mctf_supported = 1,
		.wcr_supported = 1,
		.idsp_upsample_supported = 1,
		.me0_supported = ME0_SCALE_16X,
		.enc_raw_rgb_supported = 1,
		.enc_raw_yuv_supported = 0,
		.enc_from_mem_supported = 1,
	},

	[DSP_SINGLE_REGION_WARP_MODE] = {
		.max_main = {MAX_WIDTH_IN_FULL_FPS, MAX_HEIGHT_IN_FULL_FPS},
		.min_main = {MIN_WIDTH_IN_FULL_FPS, MIN_HEIGHT_IN_FULL_FPS},
		.min_enc = {MIN_WIDTH_IN_STREAM_ROTATE, MIN_HEIGHT_IN_STREAM},
		.max_enc_num = IAV_MAX_ENCODE_STREAMS_NUM,
		.max_chroma_radius = CHROMA_RADIUS_32,
		.max_wide_chroma_radius = 0,
		.max_enc_MB = LOAD_5MP30_480P30,
		//.max_pps = MAX_CAP_PPS_IN_FULL_FPS,
		.rotate_supported = 1,
		.rawcap_supported = 0,
		.vout_swap_supported = 1,
		.lens_warp_supported = 1,
		.iso_supported = ISO_TYPE_LOW,
		.high_mp_vin_supported = 1,
		.linear_supported = 1,
		.hdr_2x_supported = HDR_TYPE_OFF,
		.hdr_3x_supported = HDR_TYPE_OFF,
		.mixer_b_supported = 1,
		.pm_bpc_supported = 1,
		.pm_mctf_supported = 1,
		.wcr_supported = 0,
		.idsp_upsample_supported = 1,
		.me0_supported = ME0_SCALE_OFF,
		.enc_raw_rgb_supported = 0,
		.enc_raw_yuv_supported = 0,
		.enc_from_mem_supported = 0,
	},

	[DSP_ADVANCED_ISO_MODE] = {
		.max_main = {MAX_WIDTH_IN_HIGH_MP, MAX_HEIGHT_IN_HIGH_MP},
		.min_main = {MIN_WIDTH_IN_HIGH_MP, MIN_HEIGHT_IN_HIGH_MP},
		.min_enc = {MIN_WIDTH_IN_STREAM_ROTATE, MIN_HEIGHT_IN_STREAM},
		.max_enc_num = IAV_MAX_ENCODE_STREAMS_NUM,
		.max_chroma_radius = CHROMA_RADIUS_128,
		.max_wide_chroma_radius = CHROMA_RADIUS_128,
		.max_enc_MB = LOAD_5MP30,
		//.max_pps = MAX_CAP_PPS_IN_FULL_FPS,
		.rotate_supported = 1,
		.rawcap_supported = 1,
		.vout_swap_supported = 1,
		.lens_warp_supported = 1,
		.iso_supported = ISO_TYPE_ADVANCED,
		.high_mp_vin_supported = 1,
		.linear_supported = 1,
		.hdr_2x_supported = HDR_TYPE_BASIC,
		.hdr_3x_supported = HDR_TYPE_OFF,
		.mixer_b_supported = 1,
		.pm_bpc_supported = 1,
		.pm_mctf_supported = 1,
		.wcr_supported = 1,
		.idsp_upsample_supported = 1,
		.me0_supported = ME0_SCALE_16X,
		.enc_raw_rgb_supported = 1,
		.enc_raw_yuv_supported = 0,
		.enc_from_mem_supported = 1,
	},

	[DSP_HDR_LINE_INTERLEAVED_MODE] = {
		.max_main = {MAX_WIDTH_IN_HIGH_MP, MAX_HEIGHT_IN_HIGH_MP},
		.min_main = {MIN_WIDTH_IN_HIGH_MP, MIN_HEIGHT_IN_HIGH_MP},
		.min_enc = {MIN_WIDTH_IN_STREAM_ROTATE, MIN_HEIGHT_IN_STREAM},
		.max_enc_num = IAV_MAX_ENCODE_STREAMS_NUM,
		.max_chroma_radius = CHROMA_RADIUS_32,
		.max_wide_chroma_radius = 0,
		.max_enc_MB = LOAD_5MP30_480P30,
		//.max_pps = MAX_CAP_PPS_IN_FULL_FPS,
		.rotate_supported = 1,
		.rawcap_supported = 1,
		.vout_swap_supported = 1,
		.lens_warp_supported = 0,
		.iso_supported = ISO_TYPE_MIDDLE,
		.high_mp_vin_supported = 1,
		.linear_supported = 0,
		.hdr_2x_supported = HDR_TYPE_ADV_WITH_CE,
		.hdr_3x_supported = HDR_TYPE_ADV_WITH_CE,
		.mixer_b_supported = 0,
		.pm_bpc_supported = 1,
		.pm_mctf_supported = 1,
		.wcr_supported = 0,
		.idsp_upsample_supported = 1,
		.me0_supported = ME0_SCALE_OFF,
		.enc_raw_rgb_supported = 0,
		.enc_raw_yuv_supported = 0,
		.enc_from_mem_supported = 0,
	},

	[DSP_HISO_VIDEO_MODE] = {
		.max_main = {MAX_WIDTH_IN_FULL_FPS, MAX_HEIGHT_IN_FULL_FPS},
		.min_main = {MIN_WIDTH_IN_FULL_FPS, MIN_HEIGHT_IN_FULL_FPS},
		.min_enc = {MIN_WIDTH_IN_STREAM, MIN_HEIGHT_IN_STREAM},
		.max_enc_num = IAV_MAX_ENCODE_STREAMS_NUM,
		.max_chroma_radius = CHROMA_RADIUS_32,
		.max_wide_chroma_radius = 0,
		.max_enc_MB = LOAD_1080P60_480P60,
		//.max_pps = MAX_CAP_PPS_IN_FULL_FPS,
		.rotate_supported = 1,
		.rawcap_supported = 1,
		.vout_swap_supported = 1,
		.lens_warp_supported = 0,
		.iso_supported = ISO_TYPE_HIGH,
		.high_mp_vin_supported = 0,
		.linear_supported = 1,
		.hdr_2x_supported = HDR_TYPE_OFF,
		.hdr_3x_supported = HDR_TYPE_OFF,
		.mixer_b_supported = 1,
		.pm_bpc_supported = 1,
		.pm_mctf_supported = 1,
		.wcr_supported = 0,
		.idsp_upsample_supported = 1,
		.me0_supported = ME0_SCALE_OFF,
		.enc_raw_rgb_supported = 1,
		.enc_raw_yuv_supported = 0,
		.enc_from_mem_supported = 0,
	},
};

struct iav_system_config G_system_config[DSP_ENCODE_MODE_TOTAL_NUM] =
{
	[DSP_NORMAL_ISO_MODE] = {
		.expo_num = 1,
		.max_stream_num = IAV_MAX_ENCODE_STREAMS_NUM,
		.max_enc_buf_num = 4,
		.debug_enable_map = 0,
		.rotatable = 0,
		.sharpen_b = 0,
		.raw_capture = 0,
		.lens_warp = 0,
		.vout_swap = 0,
		.iso_type = ISO_TYPE_LOW,
		.idsp_upsample_type = IDSP_UPSAMPLE_TYPE_OFF,
		.me0_scale = ME0_SCALE_OFF,
		.mctf_pm = 1,
		.enc_raw_rgb = 0,
		.enc_raw_yuv = 0,
		.enc_from_mem = 0,
	},

	[DSP_MULTI_REGION_WARP_MODE] = {
		.expo_num = 1,
		.max_stream_num = IAV_MAX_ENCODE_STREAMS_NUM,
		.max_enc_buf_num = 4,
		.debug_enable_map = 0,
		.rotatable = 0,
		.sharpen_b = 0,
		.raw_capture = 0,
		.lens_warp = 0,
		.vout_swap = 0,
		.iso_type = ISO_TYPE_LOW,
		.idsp_upsample_type = IDSP_UPSAMPLE_TYPE_OFF,
		.me0_scale = ME0_SCALE_OFF,
		.mctf_pm = 0,
		.enc_raw_rgb = 0,
		.enc_raw_yuv = 0,
		.enc_from_mem = 0,
	},

	[DSP_BLEND_ISO_MODE] = {
		.expo_num = 1,
		.max_stream_num = IAV_MAX_ENCODE_STREAMS_NUM,
		.max_enc_buf_num = 4,
		.debug_enable_map = 0,
		.rotatable = 0,
		.sharpen_b = 0,
		.raw_capture = 0,
		.lens_warp = 0,
		.vout_swap = 0,
		.iso_type = ISO_TYPE_BLEND,
		.idsp_upsample_type = IDSP_UPSAMPLE_TYPE_OFF,
		.me0_scale = ME0_SCALE_OFF,
		.mctf_pm = 1,
		.enc_raw_rgb = 0,
		.enc_raw_yuv = 0,
		.enc_from_mem = 0,
	},

	[DSP_SINGLE_REGION_WARP_MODE] = {
		.expo_num = 1,
		.max_stream_num = IAV_MAX_ENCODE_STREAMS_NUM,
		.max_enc_buf_num = 4,
		.debug_enable_map = 0,
		.rotatable = 0,
		.sharpen_b = 0,
		.raw_capture = 0,
		.lens_warp = 0,
		.vout_swap = 0,
		.iso_type = ISO_TYPE_LOW,

		.idsp_upsample_type = IDSP_UPSAMPLE_TYPE_OFF,
		.me0_scale = ME0_SCALE_OFF,
		.mctf_pm = 1,
		.enc_raw_rgb = 0,
		.enc_raw_yuv = 0,
		.enc_from_mem = 0,
	},

	[DSP_ADVANCED_ISO_MODE] = {
		.expo_num = 1,
		.max_stream_num = IAV_MAX_ENCODE_STREAMS_NUM,
		.max_enc_buf_num = 4,
		.debug_enable_map = 0,
		.rotatable = 0,
		.sharpen_b = 0,
		.raw_capture = 0,
		.lens_warp = 0,
		.vout_swap = 0,
		.iso_type = ISO_TYPE_ADVANCED,
		.idsp_upsample_type = IDSP_UPSAMPLE_TYPE_OFF,
		.me0_scale = ME0_SCALE_OFF,
		.mctf_pm = 1,
		.enc_raw_rgb = 0,
		.enc_raw_yuv = 0,
		.enc_from_mem = 0,
	},

	[DSP_HDR_LINE_INTERLEAVED_MODE] = {
		.expo_num = 1,
		.max_stream_num = IAV_MAX_ENCODE_STREAMS_NUM,
		.max_enc_buf_num = 4,
		.debug_enable_map = 0,
		.rotatable = 0,
		.sharpen_b = 0,
		.raw_capture = 0,
		.lens_warp = 0,
		.vout_swap = 0,
		.iso_type = ISO_TYPE_MIDDLE,
		.idsp_upsample_type = IDSP_UPSAMPLE_TYPE_OFF,
		.me0_scale = ME0_SCALE_OFF,
		.mctf_pm = 1,
		.enc_raw_rgb = 0,
		.enc_raw_yuv = 0,
		.enc_from_mem = 0,
	},

	[DSP_HISO_VIDEO_MODE] = {
		.expo_num = 1,
		.max_stream_num = IAV_MAX_ENCODE_STREAMS_NUM,
		.max_enc_buf_num = 4,
		.debug_enable_map = 0,
		.rotatable = 0,
		.sharpen_b = 0,
		.raw_capture = 0,
		.lens_warp = 0,
		.vout_swap = 0,
		.iso_type = ISO_TYPE_HIGH,
		.idsp_upsample_type = IDSP_UPSAMPLE_TYPE_OFF,
		.me0_scale = ME0_SCALE_OFF,
		.mctf_pm = 1,
		.enc_raw_rgb = 0,
		.enc_raw_yuv = 0,
		.enc_from_mem = 0,
	},
};

