##
## Kbuild
##
## History:
##    2012/01/09 - [Jian Tang] Create
##
## Copyright (C) 2012-2016, Ambarella, Inc.
##
## All rights reserved. No Part of this file may be reproduced, stored
## in a retrieval system, or transmitted, in any form, or by any means,
## electronic, mechanical, photocopying, recording, or otherwise,
## without the prior consent of Ambarella, Inc.
##

EXTRA_CFLAGS		+= $(AMBARELLA_DRV_CFLAGS)
EXTRA_AFLAGS		+= $(AMBARELLA_DRV_AFLAGS)
EXTRA_LDFLAGS		+= $(AMBARELLA_DRV_LDFLAGS)

obj-m := iav.o
iav-y := iav_drv.o iav_vout.o iav_enc_api.o iav_enc_buf.o iav_enc_perf.o iav_enc_warp.o iav_enc_bufcap.o iav_enc_pm.o iav_enc_stream.o iav_enc_limit.o \
	iav_dsp_cmd.o iav_vin.o iav_vin_pll.o iav_enc_utils.o iav_enc_pts.o iav_enc_test.o iav_netlink.o iav_dec_api.o iav_enc_mem.o iav_enc_efm.o

