#!/bin/sh
##########################
# History:
#	2015/08/19 - [Tao Wu] create file
#
# Copyright (C) 2004-2015 Ambarella, Inc.
##########################

IFNAME=$1
CMD=$2

WIFI_STATUS=/dev/console

generate_dns_conf()
{
	echo "#  DO NOT EDIT THIS FILE BY HAND " > /etc/resolv.conf
	for i in "$@"; do
		echo "nameserver $i" >> /etc/resolv.conf
	done
}

if [ "$CMD" = "CONNECTED" ]; then
    # configure network, signal DHCP client, etc.
	echo "$(date)" ":: CONNECTED"  > $WIFI_STATUS
	dns_server=$(udhcpc -i"${IFNAME}" 2>&1 |grep dns|awk '{print $3}')
	generate_dns_conf "$dns_server"
fi

if [ "$CMD" = "DISCONNECTED" ]; then
    # remove network configuration, if needed
	echo "$(date)" ":: DISCONNECTED"  > $WIFI_STATUS
fi
