/*******************************************************************************
 * am_audio_codec_aac.h
 *
 * History:
 *   2014-11-3 - [ypchang] created file
 *
 * Copyright (C) 2008-2014, Ambarella Co, Ltd.
 *
 * All rights reserved. No Part of this file may be reproduced, stored
 * in a retrieval system, or transmitted, in any form, or by any means,
 * electronic, mechanical, photocopying, recording, or otherwise,
 * without the prior consent of Ambarella.
 *
 ******************************************************************************/
#ifndef AM_AUDIO_CODEC_AAC_H_
#define AM_AUDIO_CODEC_AAC_H_

class  AMAudioCodecAacConfig;
struct AudioCodecAacConfig;

class AMAudioCodecAac: public AMAudioCodec
{
    typedef AMAudioCodec inherited;

  public:
    static AMIAudioCodec* create(const char *config);

  public:
    virtual void destroy();
    virtual bool initialize(AM_AUDIO_INFO *srcAudioInfo,
                            AM_AUDIO_CODEC_MODE mode);
    virtual bool finalize();
    virtual AM_AUDIO_INFO* get_codec_audio_info();
    virtual uint32_t get_codec_output_size();
    virtual bool get_encode_required_src_parameter(AM_AUDIO_INFO &info);
    /* encode: return generated bytes,
     * generated data size is also stored in out_data_size
     */
    virtual uint32_t encode(uint8_t *input,  uint32_t in_data_size,
                            uint8_t *output, uint32_t *out_data_size);
    /* decode: return consumed bytes,
     * generated data size is stored in out_data_size
     */
    virtual uint32_t decode(uint8_t *input,  uint32_t in_data_size,
                            uint8_t *output, uint32_t *out_data_size);

  protected:
    AMAudioCodecAac();
    virtual ~AMAudioCodecAac();
    bool init(const char *config);

  private:
    AudioCodecAacConfig   *m_aac_config; /* No need to delete */
    AMAudioCodecAacConfig *m_config;
    au_aacenc_config_t    *m_enc_conf;
    au_aacdec_config_t    *m_dec_conf;
    uint8_t               *m_enc_buffer;
    uint32_t              *m_dec_buffer;
    int32_t               *m_dec_out_buffer;
};

#endif /* AM_AUDIO_CODEC_AAC_H_ */
