##
## oryx/cgi/web_apps/make.inc
##
## History:
##    2015/08/10 - [Huaiqing Wang] Created file
##
## Copyright (C) 2012-2016, Ambarella, Inc.
##
## All rights reserved. No Part of this file may be reproduced, stored
## in a retrieval system, or transmitted, in any form, or by any means,
## electronic, mechanical, photocopying, recording, or otherwise,
## without the prior consent of Ambarella, Inc.
##

LOCAL_PATH   := $(call my-dir)
ORYX_WEB_PATH	:= $(call my-dir)
include $(CLEAR_VARS)

ifeq ($(BUILD_AMBARELLA_ORYX_WEB_APPS), y)
###############################################################################


###############################################################################
endif
