##
## Filename : Kbuild
##
## History:
##     2014/11/18 - [Long Zhao] Create
##
## Copyright (C) 2004-2014, Ambarella, Inc.
##
## All rights reserved. No Part of this file may be reproduced, stored
## in a retrieval system, or transmitted, in any form, or by any means,
## electronic, mechanical, photocopying, recording, or otherwise,
## without the prior consent of Ambarella, Inc.
##
## This file is produced by perl.
##/


EXTRA_CFLAGS		+= $(AMBARELLA_DRV_CFLAGS)
EXTRA_AFLAGS		+= $(AMBARELLA_DRV_AFLAGS)
EXTRA_LDFLAGS		+= $(AMBARELLA_DRV_LDFLAGS)

obj-m := ar0230_parallel.o
ar0230_parallel-y := ar0230.o

