##
## Filename : Kbuild
##
## History:
##    2011/01/12 - [Haowei Lo] Create
##
## Copyright (C) 2004-2011, Ambarella, Inc.
##
## All rights reserved. No Part of this file may be reproduced, stored
## in a retrieval system, or transmitted, in any form, or by any means,
## electronic, mechanical, photocopying, recording, or otherwise,
## without the prior consent of Ambarella, Inc.
##
## This file is produced by perl.
##/


EXTRA_CFLAGS		+= $(AMBARELLA_DRV_CFLAGS)
EXTRA_AFLAGS		+= $(AMBARELLA_DRV_AFLAGS)
EXTRA_LDFLAGS		+= $(AMBARELLA_DRV_LDFLAGS)

obj-m := ov5658_mipi.o
ov5658_mipi-y := ov5658.o

